Marello\Bundle\ProductBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: sku
            message: 'marello.product.messages.error.sku'
    properties:
        names:
            - Oro\Bundle\PlatformBundle\Validator\Constraints\ValidLoadedItems: ~
        sku:
            - NotBlank: ~
        prices:
            - NotBlank: ~
        suppliers:
            - Valid: ~
        salesChannelTaxCodes:
            - Valid: ~
        taxCode:
            - NotBlank: ~

Marello\Bundle\ProductBundle\Entity\ProductChannelTaxRelation:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [salesChannel, taxCode]
            errorPath: channel
            message: 'marello.productchanneltaxrelation.messages.error.unique_product_channel_tax_relation'
    properties:
        salesChannel:
            - NotBlank: ~
        taxCode:
            - NotBlank: ~

Marello\Bundle\ProductBundle\Entity\ProductSupplierRelation:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [supplier, quantityOfUnit]
            errorPath: supplier
            message: 'marello.productsupplierrelation.messages.error.unique_product_supplier_relation'
    properties:
        supplier:
            - NotBlank: ~
        quantityOfUnit:
            - NotBlank: ~