operations:
    send_packing_slip_email:
        label: marello.packing.action.send_packing_slip_email.label
        applications: [default]
        acl_resource: [EDIT, $.data]
        order: 10
        button_options:
            icon: fa-envelope
        routes:
            - marello_packing_packingslip_view
        frontend_options:
            show_dialog: true
            confirmation:
                title: marello.packing.action.send_packing_slip_email.label
                message: marello.packing.action.send_packing_slip_email.description
                message_parameters:
                    email: $.data.customer.email
                    name: $.data.customer.fullName
                component: oroui/js/standart-confirmation
        actions:
            - '@call_service_method':
                  service: oro_config.manager
                  method: get
                  method_parameters:
                      - 'marello_pdf.email_sender_email'
                      - false
                      - false
                      - '$.data.order.salesChannel'
                  attribute: '$.sender_email'
            - '@tree':
                  conditions:
                      '@not_empty': [ '$.sender_email' ]
                  actions:
                      - '@assign_value': ['$.receiver_email', '$.data.customer.email']
                      - '@assign_value': ['$.receiver_name', '$.data.customer.fullName']
                      - '@call_service_method':
                            service: oro_config.manager
                            method: get
                            method_parameters:
                                - 'marello_pdf.email_sender_name'
                                - false
                                - false
                                - '$.data.order.salesChannel'
                            attribute: '$.sender_name'
                      - '@call_service_method':
                            service: oro_config.manager
                            method: get
                            method_parameters:
                                - 'marello_pdf.email_bcc'
                                - false
                                - false
                                - '$.data.order.salesChannel'
                            attribute: '$.bcc'
                      - '@call_service_method':
                            service: translator
                            method: trans
                            method_parameters:
                                - 'marello.packing.pdf.filename.label'
                                - { '%%entityNumber%%': '$.data.packingSlipNumber' }
                            attribute: '$.filename'
                      - '@call_service_method':
                            service: marello_pdf.provider.render_parameters
                            method: getParams
                            method_parameters:
                                - '$.data'
                                - { config_scope: '$.data.salesChannel', sales_channel: '$.data.salesChannel' }
                            attribute: '$.render_parameters'
                      - '@call_service_method':
                            service: marello_pdf.renderer.twig
                            method: renderBase64
                            method_parameters:
                                - '@MarelloPacking/Pdf/packingSlip.html.twig'
                                - '$.render_parameters'
                            attribute: '$.packing_slip_pdf'
                      - '@send_email_template_attachment':
                            parameters:
                                from: { email: '$.sender_email', name: '$.sender_name' }
                                to: { email: '$.receiver_email', name: '$.receiver_name' }
                                template: marello_send_packing_slip
                                bcc: '$.bcc'
                                entity: '$.data'
                                context: '$.data.order'
                                attachments:
                                    - filename: '$.filename'
                                      body: '$.packing_slip_pdf'
                                      mimetype: 'application/pdf'
                      - '@flash_message':
                            type: 'success'
                            message: marello.packing.action.send_packing_slip_email.success
                            message_parameters:
                                '%%email%%': '$.receiver_email'
            - '@tree':
                  conditions:
                      '@empty': [ '$.sender_email' ]
                  actions:
                      - '@flash_message':
                            type: 'error'
                            message: marello.packing.action.send_packing_slip_email.error
