api:
    entity_aliases:
        Marello\Bundle\PackingBundle\Entity\PackingSlip:
            alias: marellopackingslip
            plural_alias: marellopackingslips

        Marello\Bundle\PackingBundle\Entity\PackingSlipItem:
            alias: marellopackingslipitem
            plural_alias: marellopackingslipitems

    entities:
        Marello\Bundle\PackingBundle\Entity\PackingSlip:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\PackingBundle\Entity\PackingSlipItem:
            form_options:
                validation_groups: ['api']
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
