acls:
    marello_order_create:
        type: entity
        class: MarelloOrderBundle:Order
        permission: CREATE

    marello_order_view:
        type: entity
        class: MarelloOrderBundle:Order
        permission: VIEW

    marello_order_update:
        type: entity
        class: MarelloOrderBundle:Order
        permission: EDIT
