api:
    entity_aliases:
        Marello\Bundle\OrderBundle\Entity\Customer:
            alias: marellocustomer
            plural_alias: marellocustomers

        Marello\Bundle\OrderBundle\Entity\Order:
            alias: marelloorder
            plural_alias: marelloorders

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            alias: marelloorderitem
            plural_alias: marelloorderitems

    entities:
        Marello\Bundle\OrderBundle\Entity\Order:
            documentation_resource: '@MarelloOrderBundle/Resources/doc/api/order.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orderNumber:
                        data_type: string
                        allow_array: true
                        property_path: orderNumber
                        description: 'Filter by order number'
                    orderReference:
                        data_type: string
                        allow_array: true
                        property_path: orderReference
                        description: 'Filter by order reference'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\OrderBundle\Entity\OrderItem:
            form_options:
                validation_groups: ['api']
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orders:
                        data_type: integer
                        allow_array: true
                        property_path: order
                        description: 'Filter by order ID'
            actions:
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\OrderBundle\Entity\Customer:
            documentation_resource: '@MarelloOrderBundle/Resources/doc/api/customer.md'
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    email:
                        data_type: string
                        allow_array: true
                        property_path: email
                        description: 'Filter by email'
            actions:
                delete: false
                delete_list: false
                delete_relationship: false