navigation:
    menu_config:
        items:
            orders:
                label: marello.order.entity_plural_label
                route: marello_order_order_index
                extras:
                    routes: ['marello_order_order_*']
                    position: 10

            shortcut_new_order:
                label: 'marello.order.menu.shortcut_new_order.label'
                route: 'marello_order_order_create'
                extras:
                    description: 'marello.order.menu.shortcut_new_order.description'
                    isCustomAction: true

            shortcut_list_orders:
                label: 'marello.order.menu.shortcut_list_orders.label'
                route: 'marello_order_order_index'
                extras:
                    description: 'marello.order.menu.shortcut_list_orders.description'
                    isCustomAction: true

            order_items_by_status:
                label: 'marello.order.report.order_items_by_status.label'
                route: 'marello_report_index'
                route_parameters:
                    reportGroupName: 'orders'
                    reportName:      'order_items_by_status'
                extras:
                    description: 'marello.order.report.order_items_by_status.description'
                    skipBreadcrumbs: true

            order_allocation_available_tab:
                label: 'marello.order.allocation.tab.available.label'
                extras:
                    position: 5
                    widgetAcl: 'marello_inventory_allocation_view'
                    widgetRoute: 'marello_inventory_allocation_widget'
                    widgetRouteParameters: { entityType: base, entityState: 'available' }

            order_allocation_wfs_tab:
                label: 'marello.order.allocation.tab.wfs.label'
                extras:
                    position: 10
                    widgetAcl: 'marello_inventory_allocation_view'
                    widgetRoute: 'marello_inventory_allocation_widget'
                    widgetRouteParameters: { entityType: wfs, entityState: 'waiting' }

            order_allocation_alert_tab:
                label: 'marello.order.allocation.tab.alert.label'
                extras:
                    position: 15
                    widgetAcl: 'marello_inventory_allocation_view'
                    widgetRoute: 'marello_inventory_allocation_widget'
                    widgetRouteParameters: { entityType: alert, entityState: 'alert' }

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            orders: ~
                    reports_tab:
                        children:
                            static_reports_tab:
                                children:
                                    orders_report_tab:
                                        children:
                                            order_items_by_status: ~
            shortcuts:
                children:
                    shortcut_new_order: ~
                    shortcut_list_orders: ~

            order_allocations_tab_panel:
                children:
                    order_allocation_available_tab: ~
                    order_allocation_wfs_tab: ~
                    order_allocation_alert_tab: ~
    titles:
        marello_order_order_index: marello.order.entity_plural_label
        marello_order_order_view: 'Order #%id%'
        marello_order_order_update: 'Order #%id% - Update'
        marello_order_order_create: 'New order'

