marello_order:
    resource: "@MarelloOrderBundle/Controller/OrderController.php"
    type:     annotation
    prefix:   /marello/order

marello_order_ajax:
    resource: "@MarelloOrderBundle/Controller/OrderAjaxController.php"
    type:     annotation
    prefix:   /marello/order

marello_order_dashboard:
    resource: "@MarelloOrderBundle/Controller/OrderDashboardController.php"
    type:     annotation
    prefix:   /marello/dashboard

