search:
    Marello\Bundle\OrderBundle\Entity\Order:
        alias:                          marello_order
        label:                          marello.order.entity_plural_label
        title_fields:                   [orderNumber]
        route:
            name:                       marello_order_order_view
            parameters:
                id:                     id
        search_template:                MarelloOrderBundle:Order:searchResult.html.twig
        fields:
            -
                name:                   orderNumber
                target_type:            text
                target_fields:          [orderNumber]
            -
                name:                   customer
                relation_type:          many-to-one
                relation_fields:
                    -
                        name:           email
                        target_type:    text
                        target_fields:  [email]
                    -
                        name:           firstName
                        target_type:    text
                        target_fields:  [firstName]
                    -
                        name:           lastName
                        target_type:    text
                        target_fields:  [lastName]

    Marello\Bundle\OrderBundle\Entity\Customer:
        alias:                  marello_customer
        label:                  marello.order.customer.entity_plural_label
        title_fields:           [namePrefix, firstName, middleName, lastName, nameSuffix]
        route:
            name:               marello_order_customer_view
            parameters:
                id:             id
        search_template:        MarelloOrderBundle:Customer:searchResult.html.twig
        fields:
            -
                name: namePrefix
                target_type: text
                target_fields: [namePrefix]
            -
                name: firstName
                target_type: text
                target_fields: [firstName]
            -
                name: middleName
                target_type: text
                target_fields: [middleName]
            -
                name: lastName
                target_type: text
                target_fields: [lastName]
            -
                name: nameSuffix
                target_type: text
                target_fields: [nameSuffix]
