#
# Marello config
#
fos_js_routing:
    routes_to_expose:         [marello_*]

oro_help:
    defaults:
        link: 'https://knowledgebase.marello.com/'
        server: https://knowledgebase.marello.com/
        prefix: Third_Party

oro_theme:
    active_theme: oro
    themes:
        oro:
            icon: bundles/marellolayout/images/marello.ico
            logo: bundles/marellocore/img/marello-logo.png

oro_ui:
    settings:
        organization_name:
            value:            "Marello"