placeholders:
    placeholders:
        footer_inner:
            items:
                call_on_me: ~

    items:
        call_on_me:
            template: '@@MarelloCore/call_on_me.html.twig'
            data: '@marello_core.form.url_generator->getUrl()'
