api:
    entity_aliases:
        Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder:
            alias: marellopurchaseorder
            plural_alias: marellopurchaseorders

        Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrderItem:
            alias: marellopurchaseorderitem
            plural_alias: marellopurchaseorderitems

    entities:
        Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    purchaseOrderNumber:
                        data_type: string
                        allow_array: true
                        property_path: purchaseOrderNumber
                        description: 'Filter by purchase order number'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrderItem:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    orders:
                        data_type: integer
                        allow_array: true
                        property_path: order
                        description: 'Filter by purchase order ID'
            actions:
                create: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
