system_configuration:
    fields:
        marello_purchaseorder.purchaseorder_notification:
            data_type: boolean
            type: Oro\Bundle\ConfigBundle\Form\Type\ConfigCheckbox
            options:
                label: marello.purchaseorder.system_configuration.fields.purchaseorder_notification.label
                required: false

        marello_purchaseorder.purchaseorder_notification_address:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            options:
                label: marello.purchaseorder.system_configuration.fields.purchaseorder_notification_address.label
                required: true
                constraints:
                    - NotNull: ~

    tree:
        system_configuration:
            marello:
                children:
                    notification:
                        children:
                            notification_configuration:
                                children:
                                    notification_general:
                                        children:
                                            - marello_purchaseorder.purchaseorder_notification
                                            - marello_purchaseorder.purchaseorder_notification_address
