api:
    entity_aliases:
        Marello\Bundle\SubscriptionBundle\Entity\Subscription:
            alias: marellosubscription
            plural_alias: marellosubscriptions

        Marello\Bundle\SubscriptionBundle\Entity\SubscriptionItem:
            alias: marellosubscriptionitem
            plural_alias: marellosubscriptionitems

    entities:
        Marello\Bundle\SubscriptionBundle\Entity\Subscription:
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\SubscriptionBundle\Entity\SubscriptionItem:
            actions:
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
