navigation:
    menu_config:
        items:
            subscriptions:
                label: marello.subscription.entity_plural_label
                route: marello_subscription_index
                extras:
                    routes: ['marello_subscription_*']
                    position: 45
        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            subscriptions: ~

    titles:
        marello_subscription_index: marello.subscription.entity_plural_label
        marello_subscription_view: 'Subscription #%id%'
        marello_subscription_create: 'New Subscription'
