services:
    _defaults:
        public: true

    Marello\Bundle\InvoiceBundle\Controller\InvoiceController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
