services:
    marello_invoice.mapper.abstract:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\AbstractInvoiceMapper'
        abstract: true
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'
            - '@oro_entity.doctrine_helper'

    marello_invoice.mapper.order_to_invoice:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\OrderToInvoiceMapper'
        parent: marello_invoice.mapper.abstract
        arguments:
            - '@marello_payment_term.provider.payment_term'

    marello_invoice.mapper.refund_to_creditmemo:
        class: 'Marello\Bundle\InvoiceBundle\Mapper\RefundToCreditmemoMapper'
        parent: marello_invoice.mapper.abstract

    marello_invoice.manager.invoice:
        class: 'Marello\Bundle\InvoiceBundle\Manager\InvoiceManager'
        arguments:
            - '@marello_invoice.mapper.order_to_invoice'
            - '@oro_entity.doctrine_helper'

    marello_invoice.manager.creditmemo:
        class: 'Marello\Bundle\InvoiceBundle\Manager\CreditmemoManager'
        arguments:
            - '@marello_invoice.mapper.refund_to_creditmemo'
            - '@oro_entity.doctrine_helper'

    marello_invoice.listener.invoice_create.manual:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\ManualInvoiceCreationListener'
        arguments:
            - '@marello_invoice.manager.invoice'
        tags:
            - { name: kernel.event_listener, event: extendable_action.order_invoiced, method: onInvoiced, priority: 10 }

    marello_invoice.listener.creditmemo_create.manual:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\ManualCreditmemoCreationListener'
        arguments:
            - '@marello_invoice.manager.creditmemo'
        tags:
            - { name: kernel.event_listener, event: extendable_action.refund_credited, method: onCredited, priority: 10 }

    marello_invoice.listener.datagrid.invoice_grid_address_filter_listener:
        class: 'Marello\Bundle\InvoiceBundle\EventListener\Datagrid\InvoiceGridAddressFilterListener'
        arguments:
            - '@oro_locale.dql.formatter.name'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-invoices-base-grid, method: onBuildBefore }

    marello_invoice.provider.invoice_type_choices:
        class: 'Marello\Bundle\InvoiceBundle\Provider\InvoiceTypeChoicesProvider'
