system_configuration:
    groups:
        documents:
            title: marello.pdf.config.groups.documents.label

        document_configuration:
            title: marello.pdf.config.groups.document_configuration.label
            icon: fa-file-text-o

        template:
            title: marello.pdf.config.groups.template.label

        dimensions:
            title: marello.pdf.config.groups.dimensions.label

    fields:
        marello_pdf.paper_size:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
            options:
                label: marello.pdf.config.fields.paper_size.label
                choices:
                    marello.pdf.config.fields.paper_size.a4.label: a4
                    marello.pdf.config.fields.paper_size.letter.label: letter
                constraints:
                    - Choice:
                        choices: [a4, letter]

        marello_pdf.language:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\LocaleType'
            options:
                label: marello.pdf.config.fields.language.label
                tooltip: marello.pdf.config.fields.language.tooltip
                constraints:
                    - Locale: ~

        marello_pdf.locale:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\LocaleType'
            options:
                label: marello.pdf.config.fields.locale.label
                tooltip: marello.pdf.config.fields.locale.tooltip
                constraints:
                    - Locale: ~

        marello_pdf.logo:
            data_type: string
            type: 'Oro\Bundle\ConfigBundle\Form\Type\ConfigFileType'
            options:
                label: marello.pdf.config.fields.logo.label
                tooltip: marello.pdf.config.fields.logo.tooltip
                fileConstraints:
                    - Image: ~

        marello_pdf.company_address:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
            options:
                label: marello.pdf.config.fields.company_address.label
                tooltip: marello.pdf.config.fields.company_address.tooltip

        marello_pdf.company_email:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\EmailType'
            options:
                label: marello.pdf.config.fields.company_email.label
                tooltip: marello.pdf.config.fields.company_email.tooltip
                constraints:
                    - Email: ~

        marello_pdf.company_phone:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\TextType'
            options:
                label: marello.pdf.config.fields.company_phone.label
                tooltip: marello.pdf.config.fields.company_phone.tooltip

        marello_pdf.company_bank:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
            options:
                label: marello.pdf.config.fields.company_bank.label
                tooltip: marello.pdf.config.fields.company_bank.tooltip

        marello_pdf.company_coc:
            data_type: string
            type: 'Symfony\Component\Form\Extension\Core\Type\TextareaType'
            options:
                label: marello.pdf.config.fields.company_coc.label
                tooltip: marello.pdf.config.fields.company_coc.tooltip

    tree:
        system_configuration:
            marello:
                children:
                    documents:
                        children:
                            document_configuration:
                                children:
                                    dimensions:
                                        children:
                                            - marello_pdf.paper_size
                                    template:
                                        children:
                                            - marello_pdf.language
                                            - marello_pdf.locale
                                            - marello_pdf.logo
                                            - marello_pdf.company_address
                                            - marello_pdf.company_email
                                            - marello_pdf.company_phone
                                            - marello_pdf.company_bank
                                            - marello_pdf.company_coc

        saleschannel_configuration:
            marello:
                children:
                    documents:
                        children:
                            document_configuration:
                                children:
                                    template:
                                        children:
                                            - marello_pdf.language
                                            - marello_pdf.locale
                                            - marello_pdf.logo
                                            - marello_pdf.company_address
                                            - marello_pdf.company_email
                                            - marello_pdf.company_phone
                                            - marello_pdf.company_bank
                                            - marello_pdf.company_coc
