acls:
    marelloenterprise_inventory_warehouse_view:
        type:       entity
        class:      MarelloInventoryBundle:Warehouse
        permission: VIEW

    marelloenterprise_inventory_warehouse_create:
        type:       entity
        class:      MarelloInventoryBundle:Warehouse
        permission: CREATE

    marelloenterprise_inventory_warehouse_delete:
        type:       entity
        class:      MarelloInventoryBundle:Warehouse
        permission: DELETE

    marelloenterprise_inventory_warehousechannelgrouplink_delete:
        type:       entity
        class:      MarelloInventoryBundle:WarehouseChannelGroupLink
        permission: DELETE

    marelloenterprise_inventory_warehousegroup_delete:
        type:       entity
        class:      MarelloInventoryBundle:WarehouseGroup
        permission: DELETE