operations:
    marello_delete_warehouse:
        extends: DELETE
        label: oro.action.delete
        for_all_entities: false
        for_all_datagrids: false
        routes:
            - marelloenterprise_inventory_warehouse_view
            - marelloenterprise_inventory_warehouse_update
        datagrids:
            - marelloenterprise-inventory-warehouses-grid
        preconditions: ~

    marello_delete_warehouse_group:
        extends: DELETE
        label: oro.action.delete
        for_all_entities: false
        for_all_datagrids: false
        routes:
            - marelloenterprise_inventory_warehousegroup_view
            - marelloenterprise_inventory_warehousegroup_update
        datagrids:
            - marelloenterprise-inventory-warehousegroups-grid
        preconditions: ~

    marello_delete_warehouse_channel_group_link:
        extends: DELETE
        label: oro.action.delete
        for_all_entities: false
        for_all_datagrids: false
        routes:
            - marelloenterprise_inventory_warehousechannelgrouplink_update
        datagrids:
            - marelloenterprise-inventory-warehousechannelgrouplinks-grid
        preconditions: ~

    marello_wfa_rule_enable:
        label: marelloenterprise.inventory.wfarule.datagrid.action.enable
        applications: [default]
        acl_resource: [EDIT, $.data]
        datagrids:
            - marelloenterprise-inventory-wfa-rules-grid
        routes: ~
        button_options:
            icon: fa-check
        attributes:
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preconditions:
            '@and':
                - '@equal': [$.data.rule.system, false]
                - '@equal': [$.data.rule.enabled, false]
        actions:
            - '@call_service_method':
                service: marelloenterprise_inventory.action.handler.wfa_rule.enable_status
                method: handleAction
                method_parameters: [$.data]
                attribute: $.actionSuccess
            - '@flash_message':
                conditions:
                    '@equal': [$.actionSuccess, true]
                message: marelloenterprise.inventory.wfarule.notification.enabled
                type: 'success'

    marello_wfa_rule_disable:
        label: marelloenterprise.inventory.wfarule.datagrid.action.disable
        applications: [default]
        acl_resource: [EDIT, $.data]
        datagrids:
            - marelloenterprise-inventory-wfa-rules-grid
        routes: ~
        button_options:
            icon: fa-close
        attributes:
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preconditions:
            '@and':
                - '@equal': [$.data.rule.system, false]
                - '@equal': [$.data.rule.enabled, true]
        actions:
            - '@call_service_method':
                service: marelloenterprise_inventory.action.handler.wfa_rule.disable_status
                method: handleAction
                method_parameters: [$.data]
                attribute: $.actionSuccess
            - '@flash_message':
                conditions:
                    '@equal': [$.actionSuccess, true]
                message: marelloenterprise.inventory.wfarule.notification.disabled
                type: 'success'