connector:
    name: oro_importexport
    jobs:
        marello_inventory_level_export_to_csv:
            title: "Export Inventory Level to CSV"
            type: export
            steps:
                export:
                    title:     export
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_inventory.importexport.reader.inventory_level
                        processor: oro_importexport.processor.export_delegate
                        writer:    oro_importexport.writer.csv
                    parameters: ~
        marello_inventory_level_export_template_to_csv:
            title: "Export Inventory Level Template to CSV"
            type: export_template
            steps:
                export_template:
                    title:     export_template
                    class:     Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_inventory.importexport.reader.inventory_level_template
                        processor: oro_importexport.processor.export_template_delegate
                        writer:    oro_importexport.writer.csv
                    parameters: ~