services:
    marello_payment.form_event_subscriber.method_config_collection_subscriber:
        class: 'Marello\Bundle\PaymentBundle\Form\EventSubscriber\MethodConfigCollectionSubscriber'
        arguments:
            - '@marello_payment.payment_method.composite_provider'

    marello_payment.form_event_subscriber.method_config_subscriber:
        class: 'Marello\Bundle\PaymentBundle\Form\EventSubscriber\MethodConfigSubscriber'
        arguments:
            - '@form.factory'
            - '@marello_payment.payment_method.composite_provider'

    marello_payment.form.type.method_config_collection:
        class: 'Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodConfigCollectionType'
        arguments:
            - '@marello_payment.form_event_subscriber.method_config_collection_subscriber'
        tags:
            - { name: form.type, alias: marello_payment_method_config_collection }

    marello_payment.form.type.method_config:
        class: 'Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodConfigType'
        arguments:
            - '@marello_payment.form_event_subscriber.method_config_subscriber'
            - '@marello_payment.payment_method.composite_provider'
        tags:
            - { name: form.type, alias: marello_payment_method_config }

    marello_payment.form.type.methods_configs_rule_destination:
        class: 'Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodsConfigsRuleDestinationType'
        arguments:
            - '@oro_address.form.listener.address'
        tags:
            - { name: form.type, alias: marello_payment_methods_configs_rule_destination }

    marello_payment.form.type.methods_configs_rule:
        class: 'Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodsConfigsRuleType'
        arguments:
            - '@marello_payment.provider.basic_payment_methods_choices'
            - '@translator'
        tags:
            - { name: form.type, alias: marello_payment_methods_configs_rule }

    marello_payment.form.type.payment_method_select:
        class: 'Marello\Bundle\PaymentBundle\Form\Type\PaymentMethodSelectType'
        arguments:
            - '@marello_payment.provider.basic_payment_methods_choices'
        tags:
            - { name: form.type }
