services:
    marello_payment.mass_action.status.enable:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\Actions\StatusEnableMassAction'
        arguments:
            - 'marello_payment.mass_action.status_handler'
            - 'marello_payment_methods_configs_massaction'
            - true
        shared: false
        public: true
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: paymentruleenable }

    marello_payment.mass_action.status.disable:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\Actions\StatusEnableMassAction'
        arguments:
            - 'marello_payment.mass_action.status_handler'
            - 'marello_payment_methods_configs_massaction'
            - false
        shared: false
        public: true
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: paymentruledisable }

    marello_payment.mass_action.status_handler:
        class: 'Marello\Bundle\RuleBundle\Datagrid\Extension\MassAction\StatusMassActionHandler'
        public: true
        arguments:
            - 'marello.payment.datagrid.status.success_message'
            - 'MarelloPaymentBundle:PaymentMethodsConfigsRule'
            - '@doctrine.orm.entity_manager'
            - '@translator'
