Marello\Bundle\AddressBundle\Entity\MarelloAddress:
    properties:
        street:
            - NotBlank: ~
        city:
            - NotBlank: ~
        postalCode:
            - NotBlank: ~
        country:
            - NotBlank: ~
        phone:
            - Length:
                max: 255
