Marello\Bundle\ProductBundle\Entity\Product:
     constraints:
        - Marello\Bundle\SubscriptionBundle\Validator\Constraints\SubscriptionProductAttributes: ~
#    properties:
#        subscriptionDuration:
#            - NotBlank: ~
#        paymentTerm:
#            - NotBlank: ~