parameters:
    marelloenterprise.google_api.geocoding.url: 'https://maps.googleapis.com/maps/api/geocode'
    marelloenterprise.google_api.distance_matrix.url: 'https://maps.googleapis.com/maps/api/distancematrix'

services:
    marelloenterprise.google_api.client.factory.geocoding:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Client\Factory\GoogleApiClientFactory'
        arguments:
            - '@oro_integration.transport.rest.client_factory'
            - '@oro_config.manager'
            - '%marelloenterprise.google_api.geocoding.url%'

    marelloenterprise.google_api.client.factory.distance_matrix:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Client\Factory\GoogleApiClientFactory'
        arguments:
            - '@oro_integration.transport.rest.client_factory'
            - '@oro_config.manager'
            - '%marelloenterprise.google_api.distance_matrix.url%'

    marelloenterprise.google_api.request.factory.geocoding:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Request\Factory\GeocodingApiRequestFactory'

    marelloenterprise.google_api.request.factory.distance_matrix:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Request\Factory\DistanceMatrixApiRequestFactory'
        arguments:
            - '@oro_config.manager'
            - '@marelloenterprise_address.coordinates_provider.main'

    marelloenterprise.google_api.result.factory.geocoding:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Result\Factory\GeocodingApiResultFactory'
        arguments:
            - '@logger'

    marelloenterprise.google_api.result.factory.distance_matrix:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Result\Factory\DistanceMatrixApiResultFactory'
        arguments:
            - '@logger'

    marelloenterprise.google_api.result_provider.geocoding:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Provider\GoogleApiResultsProvider'
        arguments:
            - '@marelloenterprise.google_api.request.factory.geocoding'
            - '@marelloenterprise.google_api.result.factory.geocoding'
            - '@marelloenterprise.google_api.client.factory.geocoding'

    marelloenterprise.google_api.result_provider.distance_matrix:
        class: 'MarelloEnterprise\Bundle\GoogleApiBundle\Provider\GoogleApiResultsProvider'
        arguments:
            - '@marelloenterprise.google_api.request.factory.distance_matrix'
            - '@marelloenterprise.google_api.result.factory.distance_matrix'
            - '@marelloenterprise.google_api.client.factory.distance_matrix'
