operations:
    marello_shippingmethodsconfigsrule_enable:
        label: marello.shipping.datagrid.action.enable
        applications: [default]
        acl_resource: [EDIT, $.data]
        datagrids:
            - marello-shipping-methods-configs-rule-grid
        routes: ~
        button_options:
            icon: fa-check
        attributes:
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preconditions:
            '@and':
                - '@equal': [$.data.rule.system, false]
                - '@equal': [$.data.rule.enabled, false]
        actions:
            - '@call_service_method':
                service: marello_shipping.action.handler.shipping_methods_configs_rule.enable_status
                method: handleAction
                method_parameters: [$.data]
                attribute: $.actionSuccess
            - '@flash_message':
                conditions:
                    '@equal': [$.actionSuccess, true]
                message: marello.shipping.notification.channel.enabled
                type: 'success'

    marello_shippingmethodsconfigsrule_disable:
        label: marello.shipping.datagrid.action.disable
        applications: [default]
        acl_resource: [EDIT, $.data]
        datagrids:
            - marello-shipping-methods-configs-rule-grid
        routes: ~
        button_options:
            icon: fa-close
        attributes:
            actionSuccess:
                label: oro.integration.operation.attribute.actionSuccess.label
                type: boolean
        preconditions:
            '@and':
                - '@equal': [$.data.rule.system, false]
                - '@equal': [$.data.rule.enabled, true]
        actions:
            - '@call_service_method':
                service: marello_shipping.action.handler.shipping_methods_configs_rule.disable_status
                method: handleAction
                method_parameters: [$.data]
                attribute: $.actionSuccess
            - '@flash_message':
                conditions:
                    '@equal': [$.actionSuccess, true]
                message: marello.shipping.notification.channel.disabled
                type: 'success'
