oro_entity:
    entity_aliases:
        Marello\Bundle\ShippingBundle\Entity\Shipment:
            alias: marelloshipment
            plural_alias: marelloshipments

        Marello\Bundle\ShippingBundle\Entity\ShippingMethodConfig:
            alias: marelloshippingmethodconfig
            plural_alias: marelloshippingmethodconfigs

        Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule:
            alias: marelloshippingmethodsconfigsrule
            plural_alias: marelloshippingmethodsconfigsrules

        Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestination:
            alias: marelloshippingmethodsconfigsruledestination
            plural_alias: marelloshippingmethodsconfigsruledestinations

        Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestinationPostalCode:
            alias: marelloshippingmethodsconfigsruledestinationpostalcode
            plural_alias: marelloshippingmethodsconfigsruledestinationpostalcodes

        Marello\Bundle\ShippingBundle\Entity\ShippingMethodTypeConfig:
            alias: marelloshippingmethodtypeconfig
            plural_alias: marelloshippingmethodtypeconfigs