imports:
    - { resource: controllers.yml }

services:
    Marello\Bundle\TaskBundle\Datagrid\Extension\MassAction\CloseTaskMassAction:
      shared: false
      public: true
      tags:
        - { name: oro_datagrid.extension.mass_action.type, type: closetask }

    Marello\Bundle\TaskBundle\Datagrid\Extension\MassAction\CloseTaskMassActionHandler:
        public: true
        arguments:
            - '@doctrine'
            - '@translator'

    Marello\Bundle\TaskBundle\Form\Extension\TaskExtension:
        tags:
            - { name: form.type_extension, alias: oro_task, extended_type: Oro\Bundle\TaskBundle\Form\Type\TaskType }

    marello_task.autocomplete.group.search_handler:
        class: Oro\Bundle\FormBundle\Autocomplete\SearchHandler
        parent: oro_form.autocomplete.search_handler
        arguments:
            - 'Oro\Bundle\UserBundle\Entity\Group'
            - ['name']
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: groups, acl_resource: oro_user_group_view }

    Marello\Bundle\TaskBundle\EventListener\TaskViewListener:
        arguments:
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.task-form, method: onEdit }

    Marello\Bundle\TaskBundle\EventListener\LoadTaskMetadataListener:
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    Marello\Bundle\TaskBundle\EventListener\DefaultTaskTypeListener:
        arguments:
            - '@doctrine'
        tags:
            - { name: doctrine.orm.entity_listener, entity: Oro\Bundle\TaskBundle\Entity\Task, event: prePersist }

    Marello\Bundle\TaskBundle\EventListener\RecordOwnerDataListenerDecorator:
        decorates: oro_organization.entity_ownership.listener
        arguments:
            - '@Marello\Bundle\TaskBundle\EventListener\RecordOwnerDataListenerDecorator.inner'
