marelloenterprise_inventory_warehouse:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse

marelloenterprise_inventory_warehousegroup:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseGroupController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse-group

marelloenterprise_inventory_warehousechannelgrouplink:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WarehouseChannelGroupLinkController.php"
    type:     annotation
    prefix:   /marello/inventory/warehouse-channelgroup-link

marelloenterprise_inventory_wfarule:
    resource: "@MarelloEnterpriseInventoryBundle/Controller/WFARuleController.php"
    type:     annotation
    prefix:   /marello/inventory/wfa-rule

marelloenterprise_inventory_bundle_api:
    resource: "@MarelloEnterpriseInventoryBundle/Resources/config/oro/routing_api.yml"
    type: rest
    prefix: api/rest/{version}
    requirements:
        version:  latest|v1
    defaults:
        version:  latest
