search:
    Marello\Bundle\InventoryBundle\Entity\Warehouse:
        alias:                          marello_warehouses
        title_fields:                   [label]
        route:
            name:                       marelloenterprise_inventory_warehouse_update
            parameters:
                id:                     id
        search_template: MarelloEnterpriseInventoryBundle:Warehouse:searchResult.html.twig
        fields:
            -
                name:                   label
                target_type:            text
                target_fields:          [label]

    Marello\Bundle\InventoryBundle\Entity\WarehouseGroup:
        alias:                          marello_warehousegroups
        title_fields:                   [name]
        route:
            name:                       marelloenterprise_inventory_warehousegroup_update
            parameters:
                id:                     id
        search_template: MarelloEnterpriseInventoryBundle:WarehouseGroup:searchResult.html.twig
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]