api:
    entity_aliases:
        Marello\Bundle\InvoiceBundle\Entity\Invoice:
            alias: marelloinvoice
            plural_alias: marelloinvoices

        Marello\Bundle\InvoiceBundle\Entity\InvoiceItem:
            alias: marelloinvoiceitem
            plural_alias: marelloinvoiceitems

        Marello\Bundle\InvoiceBundle\Entity\Creditmemo:
            alias: marellocreditmemo
            plural_alias: marellocreditmemos

        Marello\Bundle\InvoiceBundle\Entity\CreditmemoItem:
            alias: marellocreditmemoitem
            plural_alias: marellocreditmemoitems

    entities:
        Marello\Bundle\InvoiceBundle\Entity\Invoice:
            documentation_resource: '@MarelloInvoiceBundle/Resources/doc/api/invoice.md'
            fields:
                invoiceType:
                    exclude: true
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    order:
                        data_type: string
                        property_path: order
                        description: 'Filter by Order'
                    invoiceNumber:
                        data_type: string
                        allow_array: true
                        property_path: invoiceNumber
                        description: 'Filter by invoice number'
                    invoiceReference:
                        data_type: string
                        allow_array: true
                        property_path: invoiceReference
                        description: 'Filter by invoice reference'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\InvoiceBundle\Entity\InvoiceItem:
            form_options:
                validation_groups: ['api']
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    invoices:
                        data_type: integer
                        allow_array: true
                        property_path: invoice
                        description: 'Filter by invoice ID'
            actions:
                create: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\InvoiceBundle\Entity\Creditmemo:
            documentation_resource: '@MarelloInvoiceBundle/Resources/doc/api/creditmemo.md'
            fields:
                invoiceType:
                    exclude: true
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    order:
                        data_type: string
                        property_path: order
                        description: 'Filter by Order'
                    invoiceNumber:
                        data_type: string
                        allow_array: true
                        property_path: invoiceNumber
                        description: 'Filter by creditmemo number'
                    invoiceReference:
                        data_type: string
                        allow_array: true
                        property_path: invoiceReference
                        description: 'Filter by creditmemo reference'
                    createdAt:
                        exclude: true
                    updatedAt:
                        exclude: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false

        Marello\Bundle\InvoiceBundle\Entity\CreditmemoItem:
            form_options:
                validation_groups: ['api']
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    invoices:
                        data_type: integer
                        allow_array: true
                        property_path: invoice
                        description: 'Filter by creditmemo ID'
            actions:
                create: false
                delete: false
                delete_list: false
                update_relationship: false
                delete_relationship: false
