oro_entity:
    entity_aliases:
        Marello\Bundle\InvoiceBundle\Entity\Invoice:
            alias: marelloinvoice
            plural_alias: marelloinvoices

        Marello\Bundle\InvoiceBundle\Entity\InvoiceItem:
            alias: marelloinvoiceitem
            plural_alias: marelloinvoiceitems

        Marello\Bundle\InvoiceBundle\Entity\Creditmemo:
            alias: marellocreditmemo
            plural_alias: marellocreditmemos

        Marello\Bundle\InvoiceBundle\Entity\CreditmemoItem:
            alias: marellocreditmemoitem
            plural_alias: marellocreditmemoitems
