navigation:
    menu_config:
        items:
            invoices:
                label: marello.invoice.entity_plural_label
                route: marello_invoice_invoice_index
                extras:
                    routes: ['marello_invoice_invoice_*']
                    position: 20

        tree:
            application_menu:
                children:
                    sales_tab:
                        children:
                            invoices: ~

    titles:
        marello_invoice_invoice_index: marello.invoice.entity_plural_label
        marello_invoice_invoice_view: '%invoiceType% #%id%'