services:
    _defaults:
        public: true

    Marello\Bundle\RefundBundle\Controller\RefundAjaxController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: marello_layout.provider.form_changes_data.composite, key: Marello\Bundle\LayoutBundle\Provider\CompositeFormChangesProvider }

    Marello\Bundle\RefundBundle\Controller\RefundController:
        calls:
            - [setContainer, ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
