services:
    marello_refund.form.type.refund:
        class: Marello\Bundle\RefundBundle\Form\Type\RefundType
        tags:
            - { name: form.type }

    marello_refund.form.type.order_item_refund_collection:
        class: Marello\Bundle\RefundBundle\Form\Type\OrderItemRefundCollectionType
        tags:
            - { name: form.type }

    marello_refund.form.type.order_item_refund:
        class: Marello\Bundle\RefundBundle\Form\Type\OrderItemRefundType
        tags:
            - { name: form.type }

    marello_refund.form.type.additional_refund_collection:
        class: Marello\Bundle\RefundBundle\Form\Type\AdditionalRefundCollectionType
        tags:
            - { name: form.type }

    marello_refund.form.type.additional_refund:
        class: Marello\Bundle\RefundBundle\Form\Type\AdditionalRefundType
        tags:
            - { name: form.type }
