Marello\Bundle\RefundBundle\Entity\Refund:
    properties:
        items:
            - Valid: ~

Marello\Bundle\RefundBundle\Entity\RefundItem:
    constraints:
        - Marello\Bundle\RefundBundle\Validator\Constraints\RefundBalanceConstraint:
            message: 'marello.refund.refunditem.messages.error.refund_balance'
