Marello\Bundle\RefundBundle\Entity\Refund:
    constraints:
        - Marello\Bundle\RefundBundle\Validator\Constraints\RefundBalanceConstraint: ~
    properties:
        items:
            - Valid: ~

Marello\Bundle\RefundBundle\Entity\RefundItem:
    properties:
        refundAmount:
            -   GreaterThanOrEqual:
                    value: 0

