api:
    entity_aliases:
        MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Model\InstoreUserApi:
            alias: instoreuserapi
            plural_alias: instoreuserapi
    entities:
        MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Model\InstoreUserApi:
            documentation_resource: '@MarelloEnterpriseInstoreAssistantBundle/Resources/doc/api/instore_user_api.md'
            identifier_field_names: [id]
            fields:
                id:
                    data_type:   integer
                    description: The identifier of a UserApi.
                apiKey:
                    data_type:    string
                    description:  Api key
            actions:
                get: false
                get_list: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
                get_relationship: false
                update_relationship: false
                add_relationship: false
                delete_relationship: false