Marello\Bundle\InventoryBundle\Entity\Warehouse:
    constraints:
        - MarelloEnterprise\Bundle\InventoryBundle\Validator\Constraints\DefaultWarehouseExists: ~
        - MarelloEnterprise\Bundle\InventoryBundle\Validator\Constraints\WarehouseAddedToLinkedGroup: ~

Marello\Bundle\InventoryBundle\Entity\WarehouseChannelGroupLink:
    constraints:
        - MarelloEnterprise\Bundle\InventoryBundle\Validator\Constraints\FixedWarehouseTypeLinking: ~

Marello\Bundle\InventoryBundle\Entity\InventoryLevel:
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\UniqueEntityCollection:
            fields: [warehouse, inventoryItem]
            errorPath: warehouse
            message: 'marelloenterprise.inventory.validation.messages.error.unique_warehouse_inventory_level'
    properties:
        warehouse:
            - NotBlank: ~

MarelloEnterprise\Bundle\InventoryBundle\Entity\WFARule:
    properties:
        strategy:
            - NotBlank: ~
