oro_entity:
    entity_aliases:
        Marello\Bundle\SalesBundle\Entity\SalesChannel:
            alias: marellosaleschannel
            plural_alias: marellosaleschannels

        Marello\Bundle\SalesBundle\Entity\SalesChannelGroup:
            alias: marellosaleschannelgroup
            plural_alias: marellosaleschannelgroups

        Marello\Bundle\SalesBundle\Entity\SalesChannelType:
            alias: marellosaleschanneltype
            plural_alias: marellosaleschanneltypes