placeholders:
    placeholders:
        view_navButtons_before:
            items:
                saleschannel_config_button: ~

    items:
        saleschannel_config_button:
            template: MarelloSalesBundle:Config:button.html.twig
            applicable: "@marello_sales.placeholder.filter->isSalesChannelPage($entity$)"
