version: "2"
services:
    data:
        build:
            context: ./.docker-data
    db:
        image: percona:5.7
        expose:
            - "3306"
        container_name: subscription-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=marellocommerce
            - MYSQL_USER=marellocommerce
            - MYSQL_PASSWORD=marellocommerce
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: demo-phpmyadmin
        ports:
            - "11082:80"
        links:
            - db
        environment:
            - PMA_HOST=db

    mailhog:
        image: mailhog/mailhog
        container_name: demo-mailhog
        ports:
          - "11083:8025"
        logging:
            driver: "none"
    web:
        build:
            context: ./.docker
            args:
                - SYMFONY_ENV=prod
                - PHP_VERSION=7.3
        working_dir: /var/www/
        container_name: demo-web
        links:
            - "db"
            - "mailhog"
        ports:
            - "11080:80"
            - "11081:8080"
        volumes_from:
            - data
        volumes:
            - ../applications/demo-marello-com:/var/www:cached
            - ../package/marello:/package/marello:delegated
            - ../package/marello-enterprise:/package/marello-enterprise:delegated
            - ../package/marello-subscriptions:/package/marello-subscriptions:delegated
        environment:
            - VIRTUAL_HOST=demo.marello.docker
            - IS_LOCAL=true
            - CMD_INIT_BEFORE=
            - CMD_INIT_CLEAN=runuser -s /bin/sh -c '/usr/bin/php /var/www/bin/console oro:install --timeout 3600 --sample-data=y --drop-database --env=prod --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="marello123" --user-email="johndoe@example.com" --organization-name="Marello"' www-data
            - CMD_INIT_INSTALLED=
            - CMD_INIT_AFTER=
            - APP_DB_DRIVER=pdo_mysql
            - APP_DB_HOST=db
            - APP_DB_PORT=3306
            - APP_DB_USER=marellocommerce
            - APP_DB_PASSWORD=marellocommerce
            - APP_DB_NAME=marellocommerce
            - APP_HOSTNAME=localhost
            - APP_MAILER_TRANSPORT=smtp
            - APP_MAILER_HOST=mailhog
            - APP_MAILER_PORT=1025
            - APP_MAILER_ENCRYPTION=
            - APP_MAILER_USER=user
            - APP_MAILER_PASSWORD=password
            - APP_WEBSOCKET_HOST=
            - APP_WEBSOCKET_PORT=5081
            - APP_IS_INSTALLED=
volumes:
    dbdata:
