version: "2"
services:
    data:
        build:
            context: ./.docker-data
        container_name: marello-ee-pgsql-data
    db:
        expose:
          - "5432"
        image: postgres:9.6.9
        container_name: marello-ee-pgsql-db
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=root
            - POSTGRES_DB=marellocommerce
        volumes_from:
            - data
    #todo:: install x-delayed messages plugin for supporting correct messages in Oro
#    rabbitmq:
#        image: rabbitmq:3-management-alpine
#        ports:
#            - "5086:5672"
#            - "5087:15672"
#        environment:
#            - RABBITMQ_DEFAULT_USER=admin
#            - RABBITMQ_DEFAULT_PASS=marello123
#        volumes_from:
#            - data
    adminer:
        image: adminer
        container_name: marello-ee-pgsql-adminer
        ports:
            - "5084:8080"
        links:
            - db

    mailhog:
        image: mailhog/mailhog
        container_name: marello-ee-pgsql-mailhog
        ports:
          - "5083:8025"
        logging:
            driver: "none"

    web:
        build:
            context: ./.docker
            args:
              - SYMFONY_ENV=prod
              - COMPOSERFILE=dev.json
              - TIMEOUT=3000
        working_dir: /var/www/
        links:
            - "db"
            - "mailhog"
        container_name: marello-ee-pgsql-web
        ports:
            - "5080:80"
            - "5081:8080"
        volumes_from:
            - data
        volumes:
            - ../applications/marello-application-ee:/var/www:cached
            - ../package/marello:/package/marello
            - ../package/marello-enterprise:/package/marello-enterprise
        environment:
            - VIRTUAL_HOST=marello.docker
            - IS_LOCAL=true
            - CMD_INIT_BEFORE=
            - CMD_INIT_CLEAN=runuser -s /bin/sh -c '/usr/bin/php /var/www/bin/console oro:install --timeout 3600 --sample-data=y --drop-database --env=prod --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="marello123" --user-email="johndoe@example.com" --organization-name="Marello" --application-url="http://localhost:5080/"' www-data
            - CMD_INIT_INSTALLED=
            - CMD_INIT_AFTER=
            - APP_DB_DRIVER=pdo_pgsql
            - APP_DB_HOST=db
            - APP_DB_PORT=5432
            - APP_DB_USER=marellocommerce
            - APP_DB_PASSWORD=marellocommerce
            - APP_DB_NAME=marellocommerce
            - APP_HOSTNAME=localhost
            - APP_MAILER_TRANSPORT=smtp
            - APP_MAILER_HOST=mailhog
            - APP_MAILER_PORT=1025
            - APP_MAILER_ENCRYPTION=
            - APP_MAILER_USER=user
            - APP_MAILER_PASSWORD=password
            - APP_WEBSOCKET_HOST=
            - APP_WEBSOCKET_PORT=5081
            - APP_IS_INSTALLED=
