workflows:
    marello_order_pos_workflow:
        steps:
            pending:
                allowed_transitions:
                    - ship
                    - cancel
            cancelled:
                allowed_transitions: []
            shipped:
                allowed_transitions: []
                is_final: true