workflows:
    marello_order_pos_workflow:
        transitions:
            pending:
                step_to: pending
                is_start: true
                transition_definition: pending_definition
            cancel:
                step_to:  cancelled
                transition_definition: cancel_definition
#            payment_received:
#                step_to:  paid
#                transition_definition: payment_received_definition
#                form_options:
#                    attribute_fields:
#                        payment_reference:
#                            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
#                            options:
#                                required: true
#                                constraints:
#                                    - NotBlank: ~
#                        payment_details:
#                            form_type: Symfony\Component\Form\Extension\Core\Type\TextType
#                            options:
#                                required: true
#                                constraints:
#                                    - NotBlank: ~
#                        total_paid:
#                            form_type: Marello\Bundle\OrderBundle\Form\Type\OrderTotalPaidType
#                            options:
#                                required: true
#                                currency: $order.currency
            ship:
                step_to:  shipped
                transition_definition: ship_definition