workflows:
    marello_order_pos_workflow:
        transition_definitions:
            pending_definition:
                actions:
                    - '@assign_value':
                          - [$update_balanced_inventory, true]
                    - '@run_action_group':
                          action_group: marello_order_status_change
                          parameters_mapping:
                              order: $order
                              status: 'pending'
                    - '@extendable':
                          events: [extendable_action.order_pending]
                    - '@call_service_method':
                          service: Marello\Bundle\InventoryBundle\Provider\InventoryAllocationProvider
                          method: allocateOrderToWarehouses
                          method_parameters: [ $order ]
            ship_definition:
                actions:
                    - '@extendable':
                          events: [extendable_action.order_invoiced]
                    - '@run_action_group':
                          action_group: send_order_invoice_email
                          parameters_mapping:
                              order: $order
                              current_transition: invoice
                    - '@extendable':
                          events: [extendable_action.order_paid]
                    - '@extendable':
                          events: [extendable_action.order_ship]
                    - '@marello_ship_order': ~
                    - '@extendable':
                          events: [extendable_action.order_shipped]
                    - '@run_action_group':
                          action_group: marello_order_status_change
                          parameters_mapping:
                              order: $order
                              status: 'shipped'
            cancel_definition:
                conditions:
                    '@and':
                        - '@sales_channel_has_valid_integration':
                              salesChannel: $order.salesChannel
                actions:
                    - '@extendable':
                          events: [extendable_action.order_cancel]
                    - '@marello_cancel_order':
                          update_balanced_inventory: $update_balanced_inventory
                    - '@marello_notification_send':
                          entity: $order
                          recipient: $order.customer
                          template: marello_order_cancelled
                    - '@run_action_group':
                          action_group: send_order_invoice_email
                          parameters_mapping:
                              order: $order
                              current_transition: cancel
                    - '@run_action_group':
                          action_group: marello_order_status_change
                          parameters_mapping:
                              order: $order
                              status: 'cancelled'
