services:
    marello_commerce_bridge.workflow.action.send_email_template.marello_decorator:
        class: 'Marello\Bridge\MarelloOroCommerceApi\Workflow\Action\SendEmailTemplateMarelloDecorator'
        public: false
        decorates: oro_email.workflow.action.send_email_template
        arguments:
            - '@marello_commerce_bridge.workflow.action.send_email_template.marello_decorator.inner'

    marello_commerce_bridge.rest.request_action_handler:
        class: 'Marello\Bridge\MarelloOroCommerceApi\Request\Rest\RequestActionHandler'
        arguments:
            - ['rest']
            - '@oro_api.action_processor_bag'
            - '@oro_api.rest.filter_value_accessor_factory'
            - '@fos_rest.view_handler'

    marello_commerce_bridge.rest.request_handler:
        class: 'Marello\Bridge\MarelloOroCommerceApi\Request\Rest\RequestHandler'
        arguments:
            - '@marello_commerce_bridge.rest.request_action_handler'

    marello_commerce_bridge.create_collection.processor:
        class: Marello\Bridge\MarelloOroCommerceApi\Processor\CreateCollectionProcessor
        arguments:
            - '@oro_api.processor_bag'
            - create_collection
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'

    marello_commerce_bridge.update_collection.processor:
        class: Marello\Bridge\MarelloOroCommerceApi\Processor\UpdateCollectionProcessor
        arguments:
            - '@oro_api.processor_bag'
            - update_collection
            - '@oro_api.config_provider'
            - '@oro_api.metadata_provider'