operations:
    oro_integration_deactivate:
        label: oro.integration.deactivate
        preactions:
            - '@assign_constant_value':
                attribute: $.bankTransferType
                value: Marello\Bundle\BankTransferBundle\Integration\BankTransferChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.bankTransferType]

    oro_integration_delete:
        label: oro.integration.delete
        preactions:
            - '@assign_constant_value':
                attribute: $.bankTransferType
                value: Marello\Bundle\BankTransferBundle\Integration\BankTransferChannelType::TYPE
        preconditions:
            '@and':
                - '@not_equal': [$type, $.bankTransferType]

    marello_bank_transfer_integration_deactivate:
        label: oro.integration.deactivate
        extends: oro_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.bankTransferType
                value: Marello\Bundle\BankTransferBundle\Integration\BankTransferChannelType::TYPE
            - '@call_service_method':
                attribute: $.actionAllowed
                service: oro_integration.utils.edit_mode
                method: isSwitchEnableAllowed
                method_parameters: [$.data.editMode]
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: marello_bank_transfer.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: marello_payment.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@marello_payment_method_has_enabled_payment_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.bankTransferType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options:
            confirmation:
                title: marello.payment.integration.deactivate.title
                okText: marello.payment.integration.deactivate.button.okText
                message: marello.payment.integration.deactivate.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    marello_bank_transfer_integration_deactivate_without_rules:
        label: oro.integration.deactivate
        extends: marello_bank_transfer_integration_deactivate
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@marello_payment_method_has_enabled_payment_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.bankTransferType]
                - '@equal': [$.actionAllowed, true]
                - '@equal': [$.data.enabled, true]
        frontend_options: ~

    marello_bank_transfer_integration_delete:
        label: oro.integration.delete
        extends: oro_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preactions
            - preconditions
            - frontend_options
        preactions:
            - '@assign_constant_value':
                attribute: $.bankTransferType
                value: Marello\Bundle\BankTransferBundle\Integration\BankTransferChannelType::TYPE
            - '@call_service_method':
                service: oro_integration.utils.edit_mode
                method: isEditAllowed
                method_parameters: [$.data.editMode]
                attribute: $.actionAllowed
            - '@call_service_method':
                attribute: $.methodIdentifier
                service: marello_bank_transfer.method.identifier_generator.method
                method: generateIdentifier
                method_parameters: [$.data]
            - '@call_service_method':
                attribute: $.linkGrid
                service: marello_payment.helper.filtered_datagrid_route
                method: generate
                method_parameters:  [{'methodConfigs': $.methodIdentifier}]
        preconditions:
            '@and':
                - '@marello_payment_method_has_payment_rules':
                    parameters:
                        method_identifier: $.methodIdentifier
                - '@equal': [$type, $.bankTransferType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            confirmation:
                title: marello.payment.integration.delete.title
                okText: marello.payment.integration.delete.button.okText
                message: marello.payment.integration.delete.message
                message_parameters:
                    linkGrid: $.linkGrid
                component: oroui/js/standart-confirmation

    marello_bank_transfer_integration_delete_without_rules:
        label: oro.integration.delete
        extends: marello_bank_transfer_integration_delete
        for_all_entities: false
        for_all_datagrids: false
        replace:
            - preconditions
            - frontend_options
        preconditions:
            '@and':
                - '@not':
                    - '@marello_payment_method_has_payment_rules':
                        parameters:
                            method_identifier: $.methodIdentifier
                - '@equal': [$type, $.bankTransferType]
                - '@equal': [$.actionAllowed, true]
        frontend_options:
            title: oro.action.delete_entity
            confirmation:
                title: oro.action.delete_entity
                message: oro.action.delete_confirm
                message_parameters:
                    entityLabel: $name
                component: oroui/js/delete-confirmation
