parameters:
    marello_sales.saleschannel.entity.class:                        Marello\Bundle\SalesBundle\Entity\SalesChannel
    marello_sales.saleschannelgroup.entity.class:                   Marello\Bundle\SalesBundle\Entity\SalesChannelGroup
    marello_sales.saleschannel.model.channel_aware_interface.class: Marello\Bundle\SalesBundle\Model\SalesChannelAwareInterface

services:
    marello_sales.form.event_listener.default_sales_channel_subscriber:
        class: Marello\Bundle\SalesBundle\Form\EventListener\DefaultSalesChannelSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_sales.form.event_listener.sales_channel_form_subscriber:
        class: Marello\Bundle\SalesBundle\Form\EventListener\SalesChannelFormSubscriber
        arguments:
            - '@oro_locale.settings'

    marello_sales.saleschannel.provider.channel_provider:
        class: Marello\Bundle\SalesBundle\Provider\ChannelProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_sales.provider.basic_sales_channels_choices:
        class: Marello\Bundle\SalesBundle\Provider\BasicSalesChannelsChoicesProvider
        arguments:
            - '@oro_entity.doctrine_helper'

    marello_sales.provider.basic_sales_channels_choices.enabled_channels_decorator:
         class: Marello\Bundle\SalesBundle\Provider\EnabledSalesChannelsChoicesProviderDecorator
         public: false
         decorates: marello_sales.provider.basic_sales_channels_choices
         decoration_priority: 255
         arguments:
            - '@oro_entity.doctrine_helper'

    # Autocomplete search handler
    marello_sales.saleschannel.form.autocomplete.search_handler:
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: saleschannels, acl_resource: marello_product_view }

    marello_sales.active_saleschannels.form.autocomplete.search_handler:
        class: 'Marello\Bundle\SalesBundle\Autocomplete\ActiveSalesChannelHandler'
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name", "code", "channelType"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: active_saleschannels, acl_resource: marello_product_view }

    marello_sales.system_group_saleschannels.form.autocomplete.search_handler:
        class: 'Marello\Bundle\SalesBundle\Autocomplete\SystemGroupSalesChannelHandler'
        parent: oro_form.autocomplete.search_handler
        arguments:
            - "%marello_sales.saleschannel.entity.class%"
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: system_group_saleschannels, acl_resource: marello_product_view }

    marello_sales.repository.sales_channel:
        class: 'Marello\Bundle\SalesBundle\Entity\Repository\SalesChannelRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\SalesBundle\Entity\SalesChannel'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_sales.repository.sales_channel_group:
        class: 'Marello\Bundle\SalesBundle\Entity\Repository\SalesChannelGroupRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\SalesBundle\Entity\SalesChannelGroup'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

    marello_sales.twig.sales_extension:
        class: Marello\Bundle\SalesBundle\Twig\SalesExtension
        arguments:
            - '@marello_sales.repository.sales_channel'
        tags:
            - { name: twig.extension }

    marello_sales.event_listener.doctrine.sales_channel:
        class: 'Marello\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelListener'
        arguments:
            - '%installed%'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Marello\Bundle\SalesBundle\Entity\SalesChannel', event: prePersist }

    marello_sales.event_listener.doctrine.sales_channel_group:
        class: 'Marello\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelGroupListener'
        arguments:
            - '%installed%'
            - '@session'
        tags:
            - { name: doctrine.event_listener, event: preRemove, priority: 10 }
            - { name: doctrine.orm.entity_listener, entity: 'Marello\Bundle\SalesBundle\Entity\SalesChannelGroup', event: postPersist }

    marello_sales.event_listener.doctrine.sales_channel_group.inventory_rebalance:
        class: 'Marello\Bundle\SalesBundle\EventListener\Doctrine\SalesChannelGroupInventoryRebalanceListener'
        arguments:
            - '@oro_message_queue.client.message_producer'
        lazy:  true
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    marello_sales.event_listener.datagrid.saleschannelgroups_grid:
        class: 'Marello\Bundle\SalesBundle\EventListener\Datagrid\SalesChannelGroupDatagridListener'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.orm_datasource.result.after.marello-sales-channel-groups, method: onResultAfter }

    marello_sales.datagrid.saleschannelgroup.action_permission_provider:
        class: 'Marello\Bundle\SalesBundle\Datagrid\SalesChannelGroupActionPermissionProvider'

    marello_sales.condition.sales_channel_has_valid_integration:
        class: 'Marello\Bundle\SalesBundle\Condition\HasValidIntegration'
        arguments:
            - '@oro_integration.manager.types_registry'
        tags:
            - { name: oro_workflow.condition, alias: 'sales_channel_has_valid_integration' }
            - { name: oro_action.condition, alias: 'sales_channel_has_valid_integration' }

    marello_sales.entity_localization_provider.sales_channel:
        class: 'Marello\Bundle\SalesBundle\Provider\SalesChannelLocalizationProvider'
        tags:
            - {name: marello_entity_localization_provider, priority: 10}