datagrids:
    marello-subscriptions-grid:
        source:
            type: orm
            query:
                select:
                    - s
                    - sc.name as salesChannelName
                from:
                    - { table: MarelloSubscriptionBundle:Subscription, alias: s }
                join:
                    left:
                        salesChannel:
                            join: s.salesChannel
                            alias: sc
                        billingAddress:
                            join: s.billingAddress
                            alias: ba
                        shippingAddress:
                            join: s.shippingAddress
                            alias: sa
        columns:
            id:
                label:            marello.subscription.id.label
                renderable:       false
            subscriptionNumber:
                label:            marello.subscription.subscription_number.label
                frontend_type:    string
            startDate:
                label:            marello.subscription.start_date.label
                frontend_type:    datetime
                renderable:       false
            duration:
                label:            marello.subscription.duration.label
                frontend_type:    string
                renderable:       false
            terminationDate:
                label:            marello.subscription.termination_date.label
                frontend_type:    datetime
                renderable:       false
            terminationtNoticePeriod:
                label:            marello.subscription.termination_notice_period.label
                frontend_type:    string
                renderable:       false
            cancelBeforeDuration:
                label:            marello.subscription.cancel_before_duration.label
                frontend_type:    boolean
                renderable:       false
            renewalType:
                label:            marello.subscription.renewal_type.label
                frontend_type:    string
                renderable:       false
            salesChannel:
                label:            marello.order.sales_channel.label
                frontend_type:    string
                data_name:        salesChannelName
            shippingMethod:
                label:            marello.subscription.shipping_method.label
                type:             twig
                frontend_type:    html
                template:         MarelloOrderBundle:Order/Datagrid/Property:shippingMethod.html.twig
            paymentMethod:
                label:            marello.subscription.payment_method.label
                frontend_type:    string
                renderable:       false
            paymentFreq:
                label:            marello.subscription.payment_freq.label
                frontend_type:    string
                renderable:       false
            billingAddress:
                frontend_type:    string
                data_name:        billingName # This alias is generated using OrderGridAddressFilterListener
                label:            marello.order.billing_address.name.label
            shippingAddress:
                frontend_type:    string
                data_name:        shippingName # This alias is generated using OrderGridAddressFilterListener
                label:            marello.order.shipping_address.name.label
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
            updatedAt:
                label:            oro.ui.updated_at
                frontend_type:    datetime
        sorters:
            columns:
                subscriptionNumber:
                    data_name: s.subscriptionNumber
                startDate:
                    data_name: s.startDate
                duration:
                    data_name: s.suration
                terminationDate:
                    data_name: s.terminationDate
                terminationtNoticePeriod:
                    data_name: s.terminationtNoticePeriod
                cancelBeforeDuration:
                    data_name: s.cancelBeforeDuration
                renewalType:
                    data_name: s.renewalType
                salesChannel:
                    data_name: s.salesChannel
                shippingMethod:
                    data_name: s.shippingMethod
                paymentMethod:
                    data_name: s.paymentMethod
                paymentFreq:
                    data_name: s.paymentFreq
                billingAddress:
                    data_name: billingName
                shippingAddress:
                    data_name: shippingName
                createdAt:
                    data_name: o.createdAt
                updatedAt:
                    data_name: o.updatedAt
            default:
                orderNumber: "%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC"
        filters:
            columns:
                subscriptionNumber:
                    type: string
                    data_name: s.subscriptionNumber
                startDate:
                    type: datetime
                    data_name: s.startDate
                duration:
                    type: string
                    data_name: s.duration
                terminationDate:
                    type: datetime
                    data_name: s.terminationDate
                terminationtNoticePeriod:
                    type: string
                    data_name: s.terminationtNoticePeriod
                cancelBeforeDuration:
                    type: boolean
                    data_name: s.cancelBeforeDuration
                renewalType:
                    type: string
                    data_name: s.renewalType
                salesChannel:
                    type: string
                    data_name: s.salesChannelName
                shippingMethod:
                    type: string
                    data_name: s.shippingMethod
                paymentMethod:
                    type: string
                    data_name: s.paymentMethod
                paymentFreq:
                    type: string
                    data_name: s.paymentFreq
                billingAddress:
                    type: string
                    data_name: billingName              # This alias is generated using OrderGrdiAddressFilterListener
                shippingAddress:
                    type: string
                    data_name: shippingName             # This alias is generated using OrderGrdiAddressFilterListener
                createdAt:
                    type: datetime
                    data_name: o.createdAt
                updatedAt:
                    type: datetime
                    data_name: o.updatedAt
        properties:
            view_link:
                type:   url
                route:  marello_subscription_view
                params:
                    id: id
            update_link:
                type:   url
                route:  marello_subscription_update
                params:
                    id: id
        actions:
            view:
                type:       navigate
                label:      oro.grid.action.view
                link:       view_link
                icon:       eye
                rowAction:  true
            update:
                type:       navigate
                label:      oro.grid.action.update
                link:       update_link
                icon:       edit
                rowAction:  true
        options:
            export: true
            mass_actions:
                delete:
                    enabled: false

    marello-customer-subscriptions-grid:
        extends: marello-subscriptions-grid
        source:
            query:
                where:
                    and:
                        - s.customer = :customer_id
            bind_parameters:
                customer_id: customerId

    marello-subscription-items-grid:
        source:
            type: orm
            query:
                select:
                    - si
                from:
                    - { table: MarelloSubscriptionBundle:SubscriptionItem, alias: si }
                join:
                    left:
                        subscription:
                            join: si.subscription
                            alias: s
                where:
                    and:
                        - s.id = :subscription_id
            bind_parameters:
                subscription_id: subscriptionId
        columns:
            sku:
                label:            marello.subscription.subscriptionitem.sku.label
                frontend_type:    string
            duration:
                label:            marello.subscription.subscriptionitem.duration.label
                frontend_type:    string
            price:
                label:            marello.subscription.subscriptionitem.price.label
                frontend_type:    string
            specialPrice:
                label:            marello.subscription.subscriptionitem.special_price.label
                frontend_type:    string
            specialPriceDuration:
                label:            marello.subscription.subscriptionitem.special_price_duration.label
                frontend_type:    string

    marello-subscription-products-sales-channel-aware-grid:
        extends: marello-products-sales-channel-aware-grid
        source:
            query:
                where:
                    and:
                        - p.type = 'subscription'
