marello_subscription:
    resource: "@MarelloSubscriptionBundle/Controller/SubscriptionController.php"
    type:     annotation
    prefix:   /marello/subscription


marello_subscription_ajax:
    resource: "@MarelloSubscriptionBundle/Controller/SubscriptionAjaxController.php"
    type:     annotation
    prefix:   /marello/subscription