config:
    paths:
        'oro/select2-autocomplete-owner-aware-warehouse-group-component': 'bundles/marelloenterpriseinventory/js/app/components/select2-autocomplete-owner-aware-warehouse-group-component.js'
        'marelloenterpriseinventory/js/app/views/inventorylevel-item-view': 'bundles/marelloenterpriseinventory/js/app/views/inventorylevel-item-view.js'
