services:
    marelloenterprise_order.workflow.order_pick_pack_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderPickAndPackAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
            - '@marelloenterprise_inventory.provider.order_warehouse'
        tags:
            - { name: oro_action.action, alias: marello_pick_pack_order }

    marelloenterprise_order.workflow.order_ship_action:
        class: 'Marello\Bundle\OrderBundle\Workflow\OrderShipAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@doctrine'
            - '@event_dispatcher'
            - '@marelloenterprise_inventory.provider.order_warehouse'
        tags:
            - { name: oro_action.action, alias: marello_ship_order }