services:
    marelloenterprise_replenishment.workflow.repl_order_allocate_origin_inventory_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderAllocateOriginInventoryAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
            - '@marelloenterprise_replenishment.provider.replenishment_orders_from_config'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marelloenterprise_replenishment_order_allocate_origin_inventory_action }

    marelloenterprise_replenishment.workflow.order_ship_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderShipAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marelloenterprise_replenishment_order_ship_action }

    marelloenterprise_replenishment.workflow.repl_order_allocate_destination_inventory_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderAllocateDestinationInventoryAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
            - '@doctrine'
        tags:
            - { name: oro_action.action, alias: marelloenterprise_replenishment_order_allocate_destination_inventory_action }

    marelloenterprise_replenishment.workflow.repl_order_cancel_action:
        class: 'MarelloEnterprise\Bundle\ReplenishmentBundle\Workflow\ReplenishmentOrderCancelAction'
        arguments:
            - '@oro_action.expression.context_accessor'
            - '@event_dispatcher'
        tags:
            - { name: oro_action.action, alias: marelloenterprise_replenishment_order_cancel_action }
