dynamic-imports:
    marellopurchaseorder:
        - marellopurchaseorder/js/multiple-entity
        - marellopurchaseorder/js/multiple-entity/view
        - marellopurchaseorder/js/multiple-entity/model
        - marellopurchaseorder/js/multiple-entity/collection
        - marellopurchaseorder/js/app/components/purchaseorder-product-component
        - marellopurchaseorder/js/app/views/purchaseorder-item-view
        - marellopurchaseorder/js/app/views/purchaseorder-items-view
        - marellopurchaseorder/js/app/views/purchaseorder-totals-view
        - marellopurchaseorder/js/datagrid/marello-purchase-order-item-candidates-builder
