Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrder:
    properties:
        supplier:
            - NotBlank:
                groups: [step_one]
        items:
            - Valid: ~
        dueDate:
            - Type:
                  type: \DateTimeInterface
                  message: marello.purchaseorder.purchaseorder.due_date.type.message

Marello\Bundle\PurchaseOrderBundle\Entity\PurchaseOrderItem:
    properties:
        product:
            - NotBlank:
        orderedAmount:
            - NotBlank: ~
        purchasePrice:
            - NotBlank: ~
