Marello\Bundle\SalesBundle\Entity\SalesChannelGroup:
    constraints:
        - Marello\Bundle\Magento2Bundle\Validator\Constraints\SalesChannelsAttachedToIntegration: ~

Marello\Bundle\Magento2Bundle\Entity\Customer:
    properties:
        channel:
            - NotBlank: ~
        innerCustomer:
            - NotBlank: ~
            - Valid: ~

Marello\Bundle\Magento2Bundle\Entity\Order:
    properties:
        channel:
            - NotBlank: ~
        originId:
            - NotBlank: ~
        innerOrder:
            - NotBlank: ~
            - Valid: ~
        magentoCustomer:
            - Valid: ~

Marello\Bundle\Magento2Bundle\Entity\Website:
    properties:
        channel:
            - NotBlank: ~
        originId:
            - NotBlank: ~
        code:
            - NotBlank: ~
        name:
            - NotBlank: ~

Marello\Bundle\Magento2Bundle\Entity\Store:
    properties:
        channel:
            - NotBlank: ~
        originId:
            - NotBlank: ~
        code:
            - NotBlank: ~
        name:
            - NotBlank: ~
        website:
            - NotBlank: ~

Marello\Bundle\Magento2Bundle\Entity\ProductTaxClass:
    properties:
        channel:
            - NotBlank: ~
        originId:
            - NotBlank: ~
        className:
            - NotBlank: ~

Marello\Bundle\Magento2Bundle\Model\WebsiteToSalesChannelMapItem:
    properties:
        websiteOriginId:
            - NotBlank: ~
        websiteName:
            - NotBlank: ~
        salesChannelId:
            - NotBlank: ~
        salesChannelName:
            - NotBlank: ~
