Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRule:
    constraints:
        - Marello\Bundle\ShippingBundle\Validator\Constraints\ShippingRuleEnable: ~
    properties:
        destinations:
            - Valid: ~
        methodConfigs:
            - Valid: ~
            - Count:
                min: 1
                minMessage: marello.shipping.shippingrule.method.config.count.message
        currency:
            - Currency: ~
            - NotBlank: ~
        rule:
            - Valid: ~

Marello\Bundle\ShippingBundle\Entity\ShippingMethodsConfigsRuleDestination:
    properties:
        country:
            - NotBlank: ~
            - Valid: ~
        region:
            - Valid: ~

Marello\Bundle\ShippingBundle\Entity\ShippingMethodConfig:
    properties:
        method:
            - NotBlank: ~
        typeConfigs:
            - Valid: ~
            - Marello\Bundle\ShippingBundle\Validator\Constraints\EnabledTypeConfigsValidationGroup: ~

Marello\Bundle\ShippingBundle\Entity\ShippingMethodTypeConfig:
    properties:
        type:
            - NotBlank: ~
