services:
    marello_payment_term.payment_term.form.type:
        class: 'Marello\Bundle\PaymentTermBundle\Form\Type\PaymentTermType'
        tags:
            - { name: form.type }

    marello_payment_term.payment_term.form:
        class: 'Symfony\Component\Form\Form'
        factory: ['@form.factory', 'create']
        arguments:
            - 'Marello\Bundle\PaymentTermBundle\Form\Type\PaymentTermType'

    marello_payment_term.payment_term.form.handler:
        class: 'Marello\Bundle\PaymentTermBundle\Form\Handler\PaymentTermFormHandler'
        arguments:
            - '@marello_payment_term.payment_term.form'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    marello_payment.form_type.payment_term_choice:
        class: 'Marello\Bundle\PaymentTermBundle\Form\Type\PaymentTermChoiceType'
        arguments:
            - '@marello_payment_term.provider.payment_term'
            - '@oro_locale.helper.localization'
        tags:
            - { name: form.type }
