'Marello\Bundle\PaymentTermBundle\Entity\PaymentTerm':
    constraints:
        - 'Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity':
            fields: [code]

    properties:
        code:
            - NotBlank: ~
            - Length:
                max: 32
        term:
            - Type:
                type: integer
            - NotBlank: ~
            - Range:
                min: 0
        labels:
            - NotBlank: ~
            - Valid: ~
