imports:
    - { resource: controllers.yml }

parameters:
    marello_packing.pdf.document.total_rows:
        a4: 36
        letter: 33
    marello_packing.pdf.document.description_width:
        a4: 20
        letter: 20
    marello_packing.pdf.document.header_rows: 13
    marello_packing.pdf.document.footer_rows: 3

services:
    marello_packing.mapper.order_to_packingslip:
        class: 'Marello\Bundle\PackingBundle\Mapper\OrderToPackingSlipMapper'
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'

    marello_packing.event_listener.create_packing_slip:
        class: 'Marello\Bundle\PackingBundle\EventListener\CreatePackingSlipEventListener'
        arguments:
            - '@marello_packing.mapper.order_to_packingslip'
            - '@oro_entity.doctrine_helper'
            - '@event_dispatcher'
        tags:
            - { name: kernel.event_listener, event: extendable_action.create_packingslip, method: onCreatePackingSlip, priority: 10 }

    marello_packing.listener.datagrid.packing_slip_grid_address_filter_listener:
        class: 'Marello\Bundle\PackingBundle\EventListener\Datagrid\GridAddressFilterListener'
        arguments:
            - '@oro_locale.dql.formatter.name'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-packingslips, method: onBuildBefore }

    marello_packing.listener.datagrid.packingslipitems_batchnumbers_column_listener:
        class: 'Marello\Bundle\PackingBundle\EventListener\Datagrid\PackingslipItemsBatchNumbersColumnListener'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.marello-packingslip-items, method: onBuildAfter }

    marello_packing.listener.doctrine.packing_slip_item_status:
        class: 'Marello\Bundle\PackingBundle\EventListener\Doctrine\PackingSlipItemStatusListener'
        arguments:
            - '@oro_entity.doctrine_helper'
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    Marello\Bundle\PackingBundle\Pdf\Request\PackingSlipPdfRequestHandler:
        arguments:
            - '@doctrine'
            - '@translator'
            - '@marello_pdf.provider.render_parameters'
            - '@marello_pdf.renderer.twig'
        tags:
            - { name: marello_pdf.request_handler }

    Marello\Bundle\PackingBundle\Pdf\Table\PackingSlipTableProvider:
        arguments:
            - '@marello_packing.pdf.provider.table_size'
        tags:
            - { name: marello_pdf.document_table_provider }

    marello_packing.pdf.provider.table_size:
        class: Marello\Bundle\PdfBundle\Provider\TableSizeProvider
        arguments:
            - '@oro_config.saleschannel'
            - '%marello_packing.pdf.document.total_rows%'
            - '%marello_packing.pdf.document.description_width%'
            - '%marello_packing.pdf.document.header_rows%'
            - '%marello_packing.pdf.document.footer_rows%'
