features:
    address_geocoding:
        label: marelloenterprise.address.feature.address_geocoding.label
        description: marelloenterprise.address.feature.address_geocoding.description
        toggle: marello_enterprise_google_api.enable_google_address_geocoding
        configuration:
            - 'google_distance_matrix_settings'
        cron_jobs:
            - 'oro:cron:address-geocoding'

    address_distance_calculation_matrix_based:
        label: marelloenterprise.address.feature.distance_matrix.label
        description: marelloenterprise.address.feature.distance_matrix.description
        toggle: marello_enterprise_google_api.enable_google_distance_matrix
        dependencies:
            - 'address_geocoding'
