oro_api:
  actions:
    create_collection:
      processing_groups:
        initialize:
          priority: -10
        resource_check:
          priority: -15
        normalize_input:
          priority: -20
        security_check:
          priority: -30
        load_data:
          priority: -40
        data_security_check:
          priority: -45
        transform_data:
          priority: -50
        save_data:
          priority: -60
        normalize_data:
          priority: -70
        finalize:
          priority: -80
        normalize_result:
          priority: -90

    update_collection:
      processing_groups:
        initialize:
          priority: -10
        resource_check:
          priority: -15
        normalize_input:
          priority: -20
        security_check:
          priority: -30
        load_data:
          priority: -40
        data_security_check:
          priority: -45
        transform_data:
          priority: -50
        save_data:
          priority: -60
        normalize_data:
          priority: -70
        finalize:
          priority: -80
        normalize_result:
          priority: -90