# * POST method: creates collection of entities of the given type
# * PATCH method: updates collection of entities of the given type
oro_rest_api_collection:
    path: '%oro_api.rest.prefix%{entity}/collection'
    controller: Marello\Bridge\MarelloOroCommerceApi\Controller\RestApiController::collectionAction
    methods: [POST, PATCH]
    requirements:
        entity: (?:(?!(soap|rest)(/|$))[^/]+)
    options:
        group: rest_api
        priority: 10
