datagrids:
    marello-notificationalert-grid:
        extended_entity_name: Marello\Bundle\NotificationAlertBundle\Entity\NotificationAlert
        inline_editing:
            enable: true
            behaviour: enable_selected
        source:
            type: orm
            query:
                select:
                    - na.id
                    - at.name as alertTypeName
                    - IDENTITY(na.alertType) as alertType
                    - IDENTITY(na.resolved) as resolved
                    - IDENTITY(na.source) as source
                    - na
                from:
                    - { table: MarelloNotificationAlertBundle:NotificationAlert, alias: na }
                join:
                    inner:
                        - { join: na.alertType, alias: at }
                groupBy: na.id, at.id
        columns:
            id:
                label:            marello.notificationalert.id.label
            alertType:
                label:            marello.notificationalert.alert_type.label
                type: twig
                frontend_type:    html
                template:         '@MarelloNotificationAlert/NotificationAlert/Datagrid/Property/alertType.html.twig'
            source:
                label:            marello.notificationalert.source.label
                choices:          "@oro_entity_extend.enum_value_provider->getEnumChoicesByCode('marello_notificationalert_source')"
                frontend_type:    select
            message:
                label:            marello.notificationalert.message.label
                frontend_type:    string
            count:
                label:            marello.notificationalert.count.label
                frontend_type:    string
            resolved:
                label:            marello.notificationalert.resolved.label
                choices:          "@oro_entity_extend.enum_value_provider->getEnumChoicesByCode('marello_notificationalert_resolved')"
                frontend_type:    select
            createdAt:
                label:            oro.ui.created_at
                frontend_type:    datetime
        sorters:
            columns:
                id:
                    data_name: na.id
                alertType:
                    data_name: alertType
                count:
                    data_name: na.count
                resolved:
                    data_name: resolved
                createdAt:
                    data_name: na.createdAt
            default:
                createdAt: 'DESC'
        filters:
            columns:
                alertType:
                    type: enum
                    data_name: alertType
                    enum_code: marello_notificationalert_alerttype
                source:
                    type: enum
                    data_name: source
                    enum_code: marello_notificationalert_source
                message:
                    type: string
                    data_name: na.message
                resolved:
                    type: enum
                    data_name: resolved
                    enum_code: marello_notificationalert_resolved
                createdAt:
                    type: datetime
                    data_name: o.createdAt
        properties:
            id: ~
            view_link:
                type:   url
                route:  marello_notificationalert_view
                params:
                    id: id
            resolve_link:
                type:   url
                route:  marello_notificationalert_resolve
                params:
                    id: id
        actions:
            view:
                type:         navigate
                link:         view_link
                icon:         eye
                rowAction:    true
            resolve:
                type:         ajax
                label:        marello.notificationalert.actions.resolve.label
                link:         resolve_link
                icon:         check
                acl_resource: marello_notificationalert_update
                defaultMessages:
                    success: marello.notificationalert.actions.resolve.success
        action_configuration: ['@marello_notification_alert.datagrid.action_permission_provider', 'getNotificationAlertActionPermissions']
        mass_actions:
            resolve:
                type:         notificationalert_resolve
                acl_resource: marello_notificationalert_update
                label:        marello.notificationalert.mass_actions.resolve.label
                icon:         check
                entity_name:  'Marello\Bundle\NotificationAlertBundle\Entity\NotificationAlert'
                data_identifier: na.id
        options:
            mass_actions:
                delete:
                    enabled: false
