navigation:
    menu_config:
        items:
            notification_alerts:
                label: marello.notificationalert.entity_plural_label
                route: marello_notificationalert_index
                extras:
                    routes: ['marello_notificationalert_*']
                    position: 5

        tree:
            application_menu:
                children:
                    activities_tab:
                        children:
                            notification_alerts: ~
    titles:
        marello_notificationalert_index: marello.notificationalert.entity_plural_label
