placeholders:
    placeholders:
        marello_customer_address:
            items:
                marello_customer_address_map:
                    order: 100

    items:
        marello_customer_address_map:
            template: MarelloCustomerBundle:Customer:customerAddressMap.html.twig
