services:
    _defaults:
        public: true

    Marello\Bundle\NotificationAlertBundle\Controller\NotificationAlertController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Marello\Bundle\NotificationAlertBundle\Controller\AjaxNotificationAlertController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
