<<<<<<< HEAD
Marello\Bundle\CustomerBundle\Entity\Customer:
    properties:
        firstName:
            - NotBlank: ~
        lastName:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

Marello\Bundle\CustomerBundle\Entity\Company:
    constraints:
        - Marello\Bundle\CustomerBundle\Validator\Constraints\CompanyNumber: ~
    properties:
        name:
            - NotBlank: ~