operations:
    marello_order_can_return:
        label: marello.return.returnentity.button.label
        enabled: true
        button_options:
            class: btn-primary icons-holder-text
        routes:
            - marello_order_order_view
        acl_resource: marello_return_return_create
        applications: [default]
        preconditions:
            '@and':
                - '@extendable':
                      events: [ extendable_condition.return_allowed ]
        actions:
            - '@redirect':
                  parameters:
                      route: marello_return_return_create
                      route_parameters:
                          id: $id