services:
    marello_supplier.form.type.supplier:
        class: Marello\Bundle\SupplierBundle\Form\Type\SupplierType
        tags:
            - { name: form.type }

    marello_supplier.form.type.supplier_select:
        class: Marello\Bundle\SupplierBundle\Form\Type\SupplierSelectType
        tags:
            - { name: form.type }

    ## forms
    marello_supplier.supplier.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', 'create']
        arguments:
            - Marello\Bundle\SupplierBundle\Form\Type\SupplierType

    ## handlers
    marello_supplier.form.handler.supplier:
        class: Marello\Bundle\SupplierBundle\Form\Handler\SupplierHandler
        public: true
        arguments:
            - '@marello_supplier.supplier.form'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'
