datagrids:
    tasks-grid:
        mass_actions:
            closetask:
                type: closetask
                label: marello.task.datagrid.action.close.label
                icon: close
                acl_resource: oro_task_update
                data_identifier: task.id
                entity_name: Oro\Bundle\TaskBundle\Entity\Task
                messages:
                    success: marello.task.datagrid.action.close.message.success

    groups-select-grid:
        extended_entity_name: 'Oro\Bundle\UserBundle\Entity\Group'
        options:
            entityHint: oro.user.group.entity_plural_label
        acl_resource: oro_user_group_view
        source:
            type: orm
            query:
                select:
                    - g.id
                    - g.name
                from:
                    - { table: 'Oro\Bundle\UserBundle\Entity\Group', alias: g }
        columns:
            name:
                label: oro.user.group.name.label
        properties:
            id: ~
        sorters:
            columns:
                name:
                    data_name: g.name
            default:
                name: ASC
        filters:
            columns:
                name:
                    type: string
                    data_name: g.name
