search:
    Oro\Bundle\UserBundle\Entity\Group:
        alias:                          oro_access_group
        title_fields:                   [name]
        search_template:                '@MarelloTask/Group/Search/result.html.twig'
        route:
            name:                       oro_user_group_index
        fields:
            -
                name:                   name
                target_type:            text
                target_fields:          [name]
