oro_entity:
    entity_aliases:
        Marello\Bundle\TaxBundle\Entity\TaxCode:
            alias: marellotaxcode
            plural_alias: marellotaxcodes

        Marello\Bundle\TaxBundle\Entity\TaxRate:
            alias: marellotaxrate
            plural_alias: marellotaxrates

        Marello\Bundle\TaxBundle\Entity\TaxRule:
            alias: marellotaxrule
            plural_alias: marellotaxrules

        Marello\Bundle\TaxBundle\Entity\TaxJurisdiction:
            alias: marellotaxjurisdiction
            plural_alias: marellotaxjurisdictions
