api:
    entity_aliases:
        Marello\Bundle\CustomerBundle\Entity\Company:
            alias: marellocompany
            plural_alias: marellocompanies

    entities:
        Marello\Bundle\CustomerBundle\Entity\Company:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false