Marello\Bundle\OrderBundle\Entity\OrderItem:
    properties:
        product:
            - NotBlank: { groups: [api, Default] }
        price:
            - NotBlank: { groups: [api, Default] }
        tax:
            - NotBlank: { groups: [api, Default] }
        taxCode:
            - NotBlank: { groups: [api, Default] }
        rowTotalInclTax:
            - NotBlank: { groups: [api, Default] }
        rowTotalExclTax:
            - NotBlank: { groups: [api, Default] }
        quantity:
            - GreaterThanOrEqual: 1
    constraints:
        - Marello\Bundle\OrderBundle\Validator\Constraints\AvailableInventory:
            fields: [quantity, order, product]
            errorPath: quantity

Marello\Bundle\OrderBundle\Entity\Order:
    properties:
        customer:
            - NotBlank: { groups: [Default] }
        salesChannel:
            - NotBlank: { groups: [Default, commerce] }
        paymentMethod:
            - NotBlank: { groups: [Default, commerce] }
        shippingMethod:
            - NotBlank: { groups: [Default] }
        billingAddress:
            - NotBlank: { groups: [Default, commerce], message: 'marello.order.address.validation.billing_not_blank' }
        shippingAddress:
            - NotBlank: { groups: [Default, commerce], message: 'marello.order.address.validation.shipping_not_blank' }
        items:
            - Valid: ~
    constraints:
        - Marello\Bundle\CoreBundle\Validator\Constraints\GreaterThanDate:
            field: 'deliveryDate'
            greaterThan: 'today'
            nullable: true
            errorPath: deliveryDate
            message: 'marello.order.delivery_date.messages.error.greater_than_date'
