navigation:
    menu_config:
        items:
            replenishment:
                label: 'marelloenterprise.replenishment.menu.replenishment.label'
                route: 'marelloenterprise_replenishmentorder_index'
                extras:
                    routes: ['marelloenterprise_replenishmentorder_*']
                    position: 40
        tree:
            application_menu:
                children:
                    products_tab:
                        children:
                            inventory_management:
                                children:
                                    replenishment: ~

    titles:
        marelloenterprise_replenishmentorder_index: 'marelloenterprise.replenishment.replenishmentorder.entity_label'
