system_configuration:
    groups:
        replenishment:
            title: marelloenterprise.replenishment.system_configuration.groups.replenishment.title
        replenishment_configuration:
            title: marelloenterprise.replenishment.system_configuration.groups.replenishment_configuration.title
            icon: fa-refresh
            priority: 50
        replenishment_general:
            title: marelloenterprise.replenishment.system_configuration.groups.replenishment_general.title
            icon: fa-refresh
            priority: 50
    fields:
        marello_enterprise_replenishment.replenishment_carrier_email:
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            data_type: string
            priority: 120
            options:
                label: marelloenterprise.replenishment.system_configuration.fields.replenishment_carrier_email
                resettable: true
                required: true
                constraints:
                    - NotNull: ~

    tree:
        system_configuration:
            marello:
                children:
                    replenishment:
                        children:
                            replenishment_configuration:
                                children:
                                    replenishment_general:
                                        children:
                                            - marello_enterprise_replenishment.replenishment_carrier_email
