datagrids:
    marello-payment-methods-configs-rule-grid:
        acl_resource: marello_payment_methods_configs_rule_view
        extended_entity_name: 'Marello\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule'
        options:
            entityHint: marello.payment.paymentmethodsconfigsrule.entity_plural_label
            entity_pagination: true
        source:
            type:         orm
            query:
                select:
                    - payment_methods_configs_rule
                    - payment_methods_configs_rule.id
                    - rule.name
                    - rule.enabled
                    - rule.sortOrder
                    - payment_methods_configs_rule.currency
                from:
                    - { table: MarelloPaymentBundle:PaymentMethodsConfigsRule, alias: payment_methods_configs_rule }
                join:
                    inner:
                        - { join: payment_methods_configs_rule.rule, alias: rule }
        columns:
            id:
                label:         marello.payment.paymentmethodsconfigsrule.id.label
            name:
                label:         marello.rule.name.label
            enabled:
                label:         marello.rule.enabled.label
                frontend_type: boolean
            sortOrder:
                label:         marello.rule.sort_order.label
            currency:
                label:         marello.payment.paymentmethodsconfigsrule.currency.label
            methodConfigs:
                label:         marello.payment.paymentmethodsconfigsrule.method_configs.label
                type:          twig
                frontend_type: html
                template:      MarelloPaymentBundle:PaymentMethodsConfigsRule:Datagrid/configurations.html.twig
            destinations:
                label:         marello.payment.paymentmethodsconfigsrule.destinations.label
                type:          twig
                frontend_type: html
                template:      MarelloPaymentBundle:PaymentMethodsConfigsRule:Datagrid/destinations.html.twig
        properties:
            id: ~
            view_link:
                type:    url
                route:   marello_payment_methods_configs_rule_view
                params:  [ id ]
            update_link:
                type:    url
                route:   marello_payment_methods_configs_rule_update
                params:  [ id ]
        sorters:
            columns:
                id:
                    data_name: payment_methods_configs_rule.id
                name:
                    data_name: rule.nam
                enabled:
                   data_name: rule.enabled
                sortOrder:
                    data_name: rule.sortOrder
                currency:
                    data_name: payment_methods_configs_rule.currency
            disable_default_sorting: true
        filters:
            columns:
                id:
                    type:      number
                    data_name: payment_methods_configs_rule.id
                name:
                    type:      string
                    data_name: rule.name
                enabled:
                    type:      boolean
                    data_name: rule.enabled
                sortOrder:
                    type:      number
                    data_name: rule.sortOrder
                currency:
                    type:      string
                    data_name: payment_methods_configs_rule.currency
        actions:
            view:
                type:          navigate
                link:          view_link
                acl_resource:  marello_payment_methods_configs_rule_view
                icon:          eye
                label:         oro.grid.action.view
                rowAction:     true
        action_configuration: ['@marello_payment.datagrid.payment_rule_actions_visibility_provider', getActionsVisibility]
        mass_actions:
            enable:
                type:         paymentruleenable
                acl_resource: marello_payment_methods_configs_rule_update
                label:        marello.payment.datagrid.action.enable
                icon:         check
                entity_name:  'Marello\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule'
                data_identifier: payment_methods_configs_rule.id
            disable:
                type:         paymentruledisable
                acl_resource: marello_payment_methods_configs_rule_update
                label:        marello.payment.datagrid.action.disable
                icon:         close
                entity_name:  'Marello\Bundle\PaymentBundle\Entity\PaymentMethodsConfigsRule'
                data_identifier: payment_methods_configs_rule.id
