services:
    # finalize
    marelloenterprise_instoreassistant.api.processor.options.add_cors_response_headers:
        class: MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Processor\Options\AddCorsResponseHeaders
        tags:
            - { name: oro.api.processor, action: get, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: get_list, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: delete, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: delete_list, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: create, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: update, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: get_subresource, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: get_relationship, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: delete_relationship, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: add_relationship, group: finalize, requestType: json_api }
            - { name: oro.api.processor, action: update_relationship, group: finalize, requestType: json_api }
