acls:
    marello_paymentterm_paymentterm_create:
        type: entity
        class: MarelloPaymentTermBundle:PaymentTerm
        permission: CREATE

    marello_paymentterm_paymentterm_view:
        type: entity
        class: MarelloPaymentTermBundle:PaymentTerm
        permission: VIEW

    marello_paymentterm_paymentterm_update:
        type: entity
        class: MarelloPaymentTermBundle:PaymentTerm
        permission: EDIT

    marello_paymentterm_paymentterm_delete:
        type: entity
        class: MarelloPaymentTermBundle:PaymentTerm
        permission: DELETE
