operations:
    marello_delete_paymentterm:
        extends: DELETE
        label: oro.action.delete
        for_all_entities: false
        for_all_datagrids: false
        routes:
            - marello_paymentterm_paymentterm_view
            - marello_paymentterm_paymentterm_update
        datagrids:
            - marello-paymentterm-grid
        preactions:
            - '@tree':
                conditions:
                    '@not_blank': '$.data'
                actions:
                    - '@call_service_method':
                        service: marello_payment_term.provider.payment_term_delete_permission
                        method: isDeleteAllowed
                        method_parameters: [$.data]
                        attribute: $.isDeleteAllowed
        preconditions:
            '@and':
                - '@equal': [$.isDeleteAllowed, true]
        substitute_operation: DELETE
