api:
    entity_aliases:
        Marello\Bundle\PaymentTermBundle\Entity\PaymentTerm:
            alias: marellopaymentterm
            plural_alias: marellopaymentterms

    entities:
        Marello\Bundle\PaymentTermBundle\Entity\PaymentTerm:
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
