navigation:
    menu_config:
        items:
            payment_terms:
                label: 'marello.paymentterm.entity_plural_label'
                route: 'marello_paymentterm_paymentterm_index'

        tree:
            application_menu:
                children:
                    customers_tab:
                        children:
                            payment_terms: ~

    titles:
        marello_paymentterm_paymentterm_index: 'marello.paymentterm.entity_plural_label'
        marello_paymentterm_paymentterm_create: 'New Payment Term'
        marello_paymentterm_paymentterm_update: 'Payment Term %label% - Update'
        marello_paymentterm_paymentterm_view: 'Payment Term %label%'
