system_configuration:
    groups:
        payment:
            title: 'marello.payment_term.config.group.payment.label'
        payment_config:
            title: 'marello.payment_term.config.group.payment_config.label'
            icon: 'fa-credit-card'
        payment_term:
            title: 'marello.payment_term.config.group.payment_term.label'

    fields:
        marello_payment_term.default_payment_term:
            data_type: string
            type: 'Marello\Bundle\PaymentTermBundle\Form\Type\PaymentTermChoiceType'
            options:
                label: 'marello.payment_term.config.field.default_payment_term.label'
                tooltip: 'marello.payment_term.config.field.default_payment_term.tooltip'
                required: true
                constraints:
                    - NotNull: ~

    tree:
        system_configuration:
            marello:
                children:
                    payment:
                        children:
                            payment_config:
                                children:
                                    payment_term:
                                        children:
                                            - marello_payment_term.default_payment_term
