imports:
    - { resource: config.yml }

parameters:
    main_log_channels: []

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

doctrine:
    dbal:
        logging:            true

monolog:
    handlers:
#        detailed_logs: weedizp
#            type:           service
#            id:             oro_logger.monolog.detailed_logs.handler
#            handler:        nested
#            channels:       '%main_log_channels%'
        nested:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.log"
            level:          debug
            channels:       '%main_log_channels%'

        fingers_crossed:
            type:           fingers_crossed
            action_level:   critical
            handler:        deduplicated
            buffer_size:    1000
        deduplicated:
            type:           deduplication
            handler:        symfony_mailer
            time:           10
        symfony_mailer:
            type:           symfony_mailer
            email_prototype:
                id:         oro_logger.monolog.email_factory.error_log_notification
                method:     createEmail
            level:          debug
            formatter:      monolog.formatter.html

        # collect all log records to buffer on CLI command error
#        message_queue.consumer.console_error: weedizp
#            type:           service
#            id:             oro_message_queue.log.handler.console_error
#            handler:        nested
#            level:          debug