imports:
    - { resource: config.yml }

parameters:
    main_log_channels: []

framework:
    router:   { resource: "%kernel.project_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    ide: phpstorm
#    mailer:
#        envelope:
#            recipients: ['me@example.com']

web_profiler:
    toolbar: true
    excluded_ajax_paths: '^/((index(_[\w]+)|app(_[\w]+)?)\.php/)?(_wdt|bundles)'
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:      stream
            path:      "%kernel.logs_dir%/%kernel.environment%.log"
            level:     debug
            channels:  '%main_log_channels%'

        # collect all log records to buffer on CLI command error
#        message_queue.consumer.console_error: weedizp
#            type:      service
#            id:        oro_message_queue.log.handler.console_error
#            handler:   main
#            level:     debug

oro_message_queue:
    client:
        traceable_producer: true