services:
    Marello\Bundle\WebhookBundle\Integration\WebhookChannel:
        public: true
        tags:
            - { name: oro_integration.channel, type: marello_webhook }

    Marello\Bundle\WebhookBundle\Integration\Transport\WebhookTransport:
        public: true
        tags:
            - { name: oro_integration.transport, type: marello_webhook, channel_type: marello_webhook }

    marello_webhook.integration.connector.notification:
        class: Marello\Bundle\WebhookBundle\Integration\Connector\WebhookNotificationConnector
        arguments:
            - "@oro_importexport.context_registry"
            - "@oro_integration.logger.strategy"
            - "@oro_integration.provider.connector_context_mediator"
        tags:
            - { name: oro_integration.connector, type: marello_webhook, channel_type: marello_webhook }
