services:
    Marello\Bundle\WebhookBundle\Integration\WebhookChannel:
        public: true
        tags:
            - { name: oro_integration.channel, type: marello_webhook }

    Marello\Bundle\WebhookBundle\Integration\Transport\WebhookTransport:
        public: true
        parent: oro_integration.transport.rest.abstract_transport
        arguments:
            - '@monolog.logger'
        tags:
        - { name: oro_integration.transport, type: marello_webhook, channel_type: marello_webhook }

    Marello\Bundle\WebhookBundle\Integration\Connector\WebhookNotificationConnector:
        arguments:
            - "@oro_importexport.context_registry"
            - "@oro_integration.logger.strategy"
            - "@oro_integration.provider.connector_context_mediator"
            - '@Marello\Bundle\WebhookBundle\Model\WebhookProvider'
        tags:
            - { name: oro_integration.connector, type: marello_webhook, channel_type: marello_webhook }

    Marello\Bundle\WebhookBundle\ImportExport\Writer\WebhookExportWriter:
        arguments:
            - '@doctrine'
            - '@event_dispatcher'
            - '@oro_importexport.context_registry'
            - '@oro_integration.provider.connector_context_mediator'
            - '@Marello\Bundle\WebhookBundle\Integration\Transport\WebhookTransport'
            - '@Marello\Bundle\WebhookBundle\Model\WebhookProvider'
            - '@monolog.logger'


    # Import processors
    Marello\Bundle\WebhookBundle\ImportExport\Processor\AsyncProcessor: ~

