services:
  Marello\Bundle\WebhookBundle\Entity\Repository\WebhookRepository:
    parent: oro_entity.abstract_repository
    arguments:
      - 'Marello\Bundle\WebhookBundle\Entity\Webhook'
    tags:
      - { name: doctrine.repository_service }

  Marello\Bundle\WebhookBundle\Form\Type\WebhookType:
    tags:
      - { name: form.type }

  Marello\Bundle\WebhookBundle\Form\Type\EventSelectType:
    arguments:
      - '@oro_entity_extend.enum_value_provider'
    tags:
      - { name: form.type }

  Marello\Bundle\WebhookBundle\EventListener\WebhookEventListener:
    arguments:
      - '@Marello\Bundle\WebhookBundle\Model\WebhookProvider'
      - '@oro_message_queue.client.message_producer'
    tags:
      - { name: kernel.event_subscriber }

  Marello\Bundle\WebhookBundle\Model\WebhookProvider:
    arguments:
      - '@doctrine.orm.entity_manager'