services:
  Marello\Bundle\WebhookBundle\Entity\Repository\WebhookRepository:
    parent: oro_entity.abstract_repository
    arguments:
      - 'Marello\Bundle\WebhookBundle\Entity\Webhook'
    tags:
      - { name: doctrine.repository_service }

  Marello\Bundle\WebhookBundle\Form\Type\WebhookType:
    tags:
      - { name: form.type }

  Marello\Bundle\WebhookBundle\Form\Type\EventSelectType:
    arguments:
      - '@Marello\Bundle\WebhookBundle\Provider\WebhookEventProvider'
    tags:
      - { name: form.type }

  Marello\Bundle\WebhookBundle\EventListener\WebhookEventListener:
    arguments:
      - '@Marello\Bundle\WebhookBundle\Model\WebhookProvider'
      - '@oro_message_queue.client.message_producer'
    tags:
      - { name: kernel.event_subscriber }

  Marello\Bundle\WebhookBundle\Model\WebhookProvider:
    arguments:
      - '@doctrine.orm.entity_manager'

  Marello\Bundle\WebhookBundle\Provider\WebhookEventProvider:
    public: true

  marello_webhook.inventory.update:
    class: Marello\Bundle\WebhookBundle\Event\WebhookEventType
    arguments:
      - name: 'marello_inventory.inventory.update'
        label: 'Inventory Update'
    tags:
      - {name: marello_webhook.event}
  marello_webhook.balancedinventory.update_after:
    class: Marello\Bundle\WebhookBundle\Event\WebhookEventType
    arguments:
      - name: 'marello_inventory.balancedinventory.update_after'
        label: 'Balanced Inventory Update After'
    tags:
      - {name: marello_webhook.event}

  marello_webhook.webhook_listeners.manager:
    class: Marello\Bundle\WebhookBundle\Manager\WebhookListenerManager
    public: true
    arguments:
      - []
      - '@service_container'

  Marello\Bundle\WebhookBundle\Async\WebhookSyncProcessor:
    arguments:
      - '@oro_entity.doctrine_helper'
      - '@oro_integration.reverse_sync.processor'
      - '@oro_integration.manager.types_registry'
      - '@oro_message_queue.job.runner'
      - '@security.token_storage'
      - '@logger'
    tags:
      - { name: 'oro_message_queue.client.message_processor', topicName: !php/const Marello\Bundle\WebhookBundle\Async\Topics::WEBHOOK_NOTIFY }

  marello_webhook.importexport.cache:
    parent: oro.cache.provider.memory_cache