services:
#  Marello\Bundle\WebhookBundle\Twig\WebhookExtension:
#    arguments:
#      - '@doctrine'
#      - '@oro_security.acl_helper'
#    tags:
#      - { name: twig.extension }

  Marello\Bundle\WebhookBundle\Entity\Repository\WebhookRepository:
    parent: oro_entity.abstract_repository
    arguments:
      - 'Marello\Bundle\WebhookBundle\Entity\Webhook'
    tags:
      - { name: doctrine.repository_service }

  Marello\Bundle\WebhookBundle\Form\Type\WebhookType:
    tags:
      - { name: form.type }

  Marello\Bundle\WebhookBundle\Form\Type\EventSelectType:
    arguments:
      - '@oro_entity_extend.enum_value_provider'
    tags:
      - { name: form.type }