api:
    entity_aliases:
        Marello\Bundle\SupplierBundle\Entity\Supplier:
            alias: marellosupplier
            plural_alias: marellosuppliers

    entities:
        Marello\Bundle\SupplierBundle\Entity\Supplier:
            fields:
                createdAt:
                    exclude: true
                updatedAt:
                    exclude: true
            filters:
                exclusion_policy: all
            actions:
                delete_relationship: false
