services:
    MarelloEnterprise\Bundle\LayoutBundle\Form\Extension\FormChangesExtension:
        arguments:
            - '@oro_security.token_accessor'
        tags:
            - { name: form.type_extension }