aliases:
    oro/select2-autocomplete-company-customer-component$: marellocustomer/js/app/components/select2-autocomplete-company-customer-component
dynamic-imports:
    marellocustomer:
        - marellocustomer/js/app/components/customer-company-select-component
        - marellocustomer/js/app/components/customer-selection-component
        - marellocustomer/js/app/components/select-create-company-customer-inline-type-component
        - marellocustomer/js/app/components/select-create-company-customer-inline-type-async-component
    commons:
        - oro/select2-autocomplete-company-customer-component