parameters:
    marello_customer.entity.company.class: 'Marello\Bundle\CustomerBundle\Entity\Company'

services:
    marello_customer.repository.company:
        class: 'Marello\Bundle\CustomerBundle\Entity\Repository\CompanyRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\CustomerBundle\Entity\Company'

    marello_customer.twig.customer_extension:
        class: 'Marello\Bundle\CustomerBundle\Twig\CustomerExtension'
        arguments:
            - '@marello_customer.repository.company'
        tags:
            - { name: twig.extension }

    marello_customer.company_tree_handler:
        class: 'Marello\Bundle\CustomerBundle\JsTree\CompanyTreeHandler'
        public: true
        arguments:
            - '%marello_customer.entity.company.class%'
            - "@doctrine"

    marello_customer.listener.datagrid.company_customers_column_listener:
        class: 'Marello\Bundle\CustomerBundle\EventListener\Datagrid\CompanyCustomersColumnListener'
        arguments:
            - '@marello_datagrid.datagridhelper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-company-customers-extend-grid, method: buildBefore }

    marello_customer.form.autocomplete.company.search_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%marello_customer.entity.company.class%'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: marello_customer_company, acl_resource: marello_customer_company_view }

    marello_customer.form.autocomplete.company_parent.search_handler:
        public: false
        parent: oro_form.autocomplete.search_handler
        class: 'Marello\Bundle\CustomerBundle\Autocomplete\ParentCompanySearchHandler'
        arguments:
            - '%marello_customer.entity.company.class%'
            - ["name"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: marello_company_parent, acl_resource: marello_customer_company_view }

    marello_customer.form.type.company_select:
        class: 'Marello\Bundle\CustomerBundle\Form\Type\CompanySelectType'
        tags:
            - { name: form.type }

    marello_customer.form.type.company:
        class: 'Marello\Bundle\CustomerBundle\Form\Type\CompanyType'
        arguments:
          - '@security.authorization_checker'
        tags:
            - { name: form.type }

    marello_customer.form.type.parent_company_select:
        class: 'Marello\Bundle\CustomerBundle\Form\Type\ParentCompanySelectType'
        tags:
            - { name: form.type }

    marello_customer.company.form:
        class: 'Symfony\Component\Form\Form'
        factory: ['@form.factory', 'create']
        arguments:
            - 'Marello\Bundle\CustomerBundle\Form\Type\CompanyType'

    marello_customer.company.form.handler:
        class: 'Marello\Bundle\CustomerBundle\Form\Handler\CompanyHandler'
        public: true
        arguments:
            - '@marello_customer.company.form'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'