oro_entity:
    entity_aliases:
        Marello\Bundle\ServicePointBundle\Entity\ServicePoint:
            alias: marelloservicepoint
            plural_alias: marelloservicepoints

        Marello\Bundle\ServicePointBundle\Entity\Facility:
            alias: marellofacility
            plural_alias: marellofacilities

        Marello\Bundle\ServicePointBundle\Entity\ServicePointFacility:
            alias: marelloservicepointfacility
            plural_alias: marelloservicepointfacilities

        Marello\Bundle\ServicePointBundle\Entity\ServicePointAddress:
            alias: marelloservicepointaddress
            plural_alias: marelloservicepointaddresses

        Marello\Bundle\ServicePointBundle\Entity\TimePeriod:
            alias: marellotimeperiod
            plural_alias: marellotimeperiods
