marello_servicepoint_facility:
    resource:     "@MarelloServicePointBundle/Controller/FacilityController.php"
    type:         annotation
    prefix:       /marello/servicepoint/facility

marello_servicepoint_servicepoint:
    resource:     "@MarelloServicePointBundle/Controller/ServicePointController.php"
    type:         annotation
    prefix:       /marello/servicepoint/servicepoint

marello_servicepoint_servicepointfacility:
    resource:     "@MarelloServicePointBundle/Controller/ServicePointFacilityController.php"
    type:         annotation
    prefix:       /marello/servicepoint/servicepointfacility
