aliases:
    oro/datagrid/cell/boolean-select-row-cell$: marellodatagrid/js/datagrid/cell/boolean-select-row-cell
dynamic-imports:
    marellocustomer:
        - marellodatagrid/js/datagrid/listener/select-all-listener
        - marellodatagrid/js/datagrid/listener/column-form-listener
        - marellodatagrid/js/datagrid/header-cell/select-all-header-cell
        - marellocustomer/js/app/components/select-create-company-customer-inline-type-async-component
    commons:
        - oro/datagrid/cell/boolean-select-row-cell
#config:
#    paths:
#        'oro/datagrid/cell/boolean-select-row-cell': 'bundles/marellodatagrid/js/datagrid/cell/boolean-select-row-cell.js'
#        'marellodatagrid/js/datagrid/listener/select-all-listener': 'bundles/marellodatagrid/js/datagrid/listener/select-all-listener.js'
#        'marellodatagrid/js/datagrid/listener/column-form-listener': 'bundles/marellodatagrid/js/datagrid/listener/column-form-listener.js'
#        'marellodatagrid/js/datagrid/header-cell/select-all-header-cell': 'bundles/marellodatagrid/js/datagrid/header-cell/select-all-header-cell.js'