parameters:
    marello_catalog.category.entity.class: Marello\Bundle\CatalogBundle\Entity\Category
services:
    marello_catalog.category.form.type:
        class: 'Marello\Bundle\CatalogBundle\Form\Type\CategoryType'
        arguments:
            - '@marello_catalog.formatter.category_code'
        tags:
            - { name: form.type }

    marello_catalog.category.form:
        class: 'Symfony\Component\Form\Form'
        factory: ['@form.factory', 'create']
        arguments:
            - 'Marello\Bundle\CatalogBundle\Form\Type\CategoryType'

    marello_catalog.category.form.handler:
        class: 'Marello\Bundle\CatalogBundle\Form\Handler\CategoryHandler'
        public: true
        arguments:
            - '@marello_catalog.category.form'
            - '@request_stack'
            - '@doctrine.orm.entity_manager'

    marello_catalog.event_listener.datagrid.products_grid:
        class: 'Marello\Bundle\CatalogBundle\EventListener\Datagrid\CategoriesDatagridListener'
        arguments:
            - '%marello_product.entity.class%'
            - '@marello_catalog.provider.categories_choices'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-products-grid, method: onBuildBefore }

    marello_catalog.listener.datagrid.category_products_column_listener:
        class: 'Marello\Bundle\CatalogBundle\EventListener\Datagrid\CategoryProductsColumnListener'
        arguments:
            - '@marello_datagrid.datagridhelper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-category-products-extend-grid, method: buildBefore }

    marello_catalog.formatter.category_code:
        class: 'Marello\Bundle\CatalogBundle\Formatter\CategoryCodeFormatter'

    marello_catalog.provider.categories_choices:
        class: 'Marello\Bundle\CatalogBundle\Provider\CategoriesChoicesProvider'
        public: true
        arguments:
            - '@oro_entity.doctrine_helper'

    marello_catalog.provider.categories_ids:
        class: 'Marello\Bundle\CatalogBundle\Provider\CategoriesIdsProvider'
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_catalog.repository.category:
        class: 'Marello\Bundle\CatalogBundle\Entity\Repository\CategoryRepository'
        parent: oro_entity.abstract_repository
        arguments:
            - 'Marello\Bundle\CatalogBundle\Entity\Category'
        calls:
            - [setAclHelper, ['@oro_security.acl_helper']]

