api:
    entity_aliases:
        Marello\Bundle\ProductBundle\Entity\Product:
            alias: marelloproduct
            plural_alias: marelloproducts

        Marello\Bundle\ProductBundle\Entity\ProductStatus:
            alias: marelloproductstatus
            plural_alias: marelloproductstatuses

    entities:
        Marello\Bundle\ProductBundle\Entity\Product:
            documentation_resource: '@MarelloProductBundle/Resources/doc/api/product.md'
            identifier_field_names: [sku]
            fields:
                saleschannels:
                    property_path: channels
                taxcode:
                    property_path: taxCode
                productstatus:
                    property_path: status
                channelsCodes:
                    exclude: true
                categoriesCodes:
                    exclude: true
            filters:
                exclusion_policy: all
                fields:
                    sku:
                        data_type: string
                        allow_array: true
                        property_path: sku
                        description: 'Filter by sku'
                    saleschannels:
                        data_type: string
                        allow_array: true
                        property_path: channels.code
                        description: 'Filter products by SalesChannel'
                    createdAt:
                        data_type: datetime
                        property_path: createdAt
                        description: 'Filter products by created at'
                    updatedAt:
                        data_type: datetime
                        property_path: updatedAt
                        description: 'Filter products by updated at'
            actions:
                create:
                    fields:
                        prices:
                            exclude: true
                        channelPrices:
                            exclude: true