liip_imagine:
    loaders:
        default:
            filesystem:
                bundle_resources:
                    enabled: true
    filter_sets:
        cache : ~
        product_grid:
            quality:          95
            filters:
                thumbnail:    { size: [35, 35], mode: inset }
                strip:        ~
        product_view:
            quality:          95
            filters:
                thumbnail:    { size: [250, 250], mode: inset }
                strip:        ~