parameters:
    marello_locale.repository.email_template_translatable.class: Marello\Bundle\LocaleBundle\Repository\EmailTemplateTranslatableRepository
    marello_locale.manager.email_template.class: Marello\Bundle\LocaleBundle\Manager\EmailTemplateManager

services:
    marello_locale.repository.email_template_translatable_repository:
        class: '%marello_locale.repository.email_template_translatable.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_locale.manager.email_template:
        class: '%marello_locale.manager.email_template.class%'
        arguments:
            - '@marello_locale.repository.email_template_translatable_repository'
            - '@oro_config.user'
        calls:
            - ['setEntityLocalizationProvider', ['@marello_locale.entity_localization_provider.chain']]

    marello_locale.entity_localization_provider.chain:
        class: 'Marello\Bundle\LocaleBundle\Provider\ChainEntityLocalizationProvider'

    marello_locale.entity_localization_provider.default:
        class: 'Marello\Bundle\LocaleBundle\Provider\DefaultEntityLocalizationProvider'
        arguments:
            - '@oro_config.manager'
            - '@oro_entity.doctrine_helper'
        tags:
            - {name: marello_entity_localization_provider, priority: 0}