navigation:
    menu_config:
        items:
            servicepoints_tab:
                label: 'marello.servicepoint.entity_plural_label'
                uri: '#'
                extras:
                    icon: 'fa fa-map-marker'
                    position: 50

            facilities:
                label: 'marello.servicepoint.facility.entity_plural_label'
                route: 'marello_servicepoint_facility_index'

            servicepoints:
                label: 'marello.servicepoint.entity_plural_label'
                route: 'marello_servicepoint_servicepoint_index'

        tree:
            application_menu:
                children:
                    servicepoints_tab:
                        children:
                            facilities: ~
                            servicepoints: ~

    titles:
        marello_servicepoint_facility_index: 'marello.servicepoint.facility.entity_plural_label'
        marello_servicepoint_facility_create: 'New Facility'
        marello_servicepoint_facility_update: 'Facility %label% - Update'

        marello_servicepoint_servicepoint_index: 'marello.servicepoint.entity_plural_label'
        marello_servicepoint_servicepoint_create: 'New Service Point'
        marello_servicepoint_servicepoint_update: 'Service Point %label% - Update'
        marello_servicepoint_servicepoint_view: 'Service Point %label%'

        marello_servicepoint_servicepointfacility_index: 'marello.servicepoint.servicepoint_facility.entity_plural_label'
        marello_servicepoint_servicepointfacility_create: 'New Service Point Facility'
        marello_servicepoint_servicepointfacility_update: 'Service Point Facility %facility% - Update'
        marello_servicepoint_servicepointfacility_view: 'Service Point Facility %facility%'
