services:
    marello_return.form.type.return:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnType
        arguments:
            - '@marello_return.form.event_listener.return_type_subscriber'
        tags:
            - { name: form.type }

    marello_return.form.type.return_update:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnUpdateType
        tags:
            - { name: form.type }

    marello_return.form.type.return_item:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemType
        tags:
            - { name: form.type }
        arguments:
            - '@marello_return.form.event_listener.return_item_type_subscriber'

    marello_return.form.type.return_item_collection:
        class: Marello\Bundle\ReturnBundle\Form\Type\ReturnItemCollectionType
        tags:
            - { name: form.type }

    marello_return.form.event_listener.return_type_subscriber:
        class: Marello\Bundle\ReturnBundle\Form\EventListener\ReturnTypeSubscriber

    marello_return.form.event_listener.return_item_type_subscriber:
        class: Marello\Bundle\ReturnBundle\Form\EventListener\ReturnItemTypeSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'

    marello_return.form.data_transformer.order_to_order_number:
        class: Marello\Bundle\ReturnBundle\Form\DataTransformer\OrderToOrderNumberTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
