services:
    marello_report.listener.datagrid.workflow_grid_listener:
        class: '%marello_datagrid.event_listener.datagrid.workflow_grid_listener.class%'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.marello_report-orders-revenue_per_sales_channel, method: removeWorkflow }

    marello_report.listener.datagrid.returns_returned_by_reason_listener:
        class: Marello\Bundle\ReportBundle\EventListener\Datagrid\ReturnsReturnedByReasonReportListener
        arguments:
            - '@marello_return.repository.return_item'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.after.marello_report-returns-returned_qty_by_reason, method: onBuildAfter }