system_configuration:
    groups:
        webhook_settings:
            title: marello.webhook.system_configuration.groups.webhook.title
        webhook_integration_settings:
            title: marello.webhook.system_configuration.groups.settings.title
            icon: 'fa-file'
        integration_setting:
            title: marello.webhook.system_configuration.groups.settings_mapping.title
            icon: 'fa-user-plus'

    fields:
        marello_webhook.notification_redelivery:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            search_type: text
            priority: 60
            options:
                label: marello.webhook.system_configuration.fields.notification_redelivery.label
                required: false

    tree:
        system_configuration:
            platform:
                children:
                    integrations: # TODO do we need to move to Marello section?
                        children:
                            webhook_settings:
                                children:
                                    webhook_integration_settings:
                                        children:
                                            - marello_webhook.notification_redelivery
