parameters:
    marello_subscription.entity.subscription.class: Marello\Bundle\SubscriptionBundle\Entity\Subscription
    marello_subscription.entity.subscription_item.class: Marello\Bundle\SubscriptionBundle\Entity\SubscriptionItem

services:
    marello_subscription.product_type.subscription:
        class: 'Marello\Bundle\ProductBundle\Model\ProductType'
        arguments:
            - name: 'subscription'
              label: 'Subscription'
              attribute_family_code: 'marello_subscription'
        tags:
            - {name: marello_product.product_type}

    marello_subscription.form.autocomplete.sales_channel_subscription_products.search_handler:
        class: 'Marello\Bundle\SubscriptionBundle\Autocomplete\SalesChannelSubscriptionProductsHandler'
        parent: oro_form.autocomplete.search_handler
        arguments:
            - '%marello_product.entity.class%'
            - ["name", "sku"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: sales_channel_subscription_products, acl_resource: marello_product_view }

    marello_subscription.form.type.address:
        arguments:
            - '@oro_locale.formatter.address'
            - '@marello_order.provider.customer_address'
            - '@oro_importexport.serializer'
        abstract: true

    marello_subscription.form.type.shipping_address:
        parent: 'marello_subscription.form.type.address'
        class: 'Marello\Bundle\SubscriptionBundle\Form\Type\SubscriptionShippingAddressType'
        tags:
            - { name: form.type }

    marello_subscription.form.type.billing_address:
        parent: 'marello_subscription.form.type.address'
        class: 'Marello\Bundle\SubscriptionBundle\Form\Type\SubscriptionBillingAddressType'
        tags:
            - { name: form.type }

    marello_subscription.form.type.subscription:
        class: 'Marello\Bundle\SubscriptionBundle\Form\Type\SubscriptionType'
        arguments:
            - '@marello_subscription.form.event_listener.subscription_item'
        tags:
            - { name: form.type }

    marello_subscription.form.type._update:
        class: 'Marello\Bundle\SubscriptionBundle\Form\Type\SubscriptionUpdateType'
        tags:
            - { name: form.type }

    marello_subscription.form.type.subscription_product_sales_channel_aware_select:
        class: 'Marello\Bundle\SubscriptionBundle\Form\Type\SubscriptionProductSalesChannelAwareSelectType'
        tags:
            - { name: form.type }

    marello_subscription.form.event_listener.subscription_item:
        class: 'Marello\Bundle\SubscriptionBundle\Form\EventListener\SubscriptionItemSubscriber'

    marello_subscription.form.event_listener.subscription_product:
        class: 'Marello\Bundle\SubscriptionBundle\Form\EventListener\SubscriptionProductSubscriber'

    marello_subscription.provider.form_changes.billing_address:
        class: 'Marello\Bundle\OrderBundle\Provider\OrderAddressFormChangesProvider'
        arguments:
            - '@templating'
            - '@form.factory'
            - 'billing'
        tags:
            - { name: marello.form_changes_data_provider, class: '%marello_subscription.entity.subscription.class%', type: billingAddress, priority: 20 }

    marello_subscription.provider.form_changes.shipping_address:
        class: 'Marello\Bundle\OrderBundle\Provider\OrderAddressFormChangesProvider'
        arguments:
            - '@templating'
            - '@form.factory'
            - 'shipping'
        tags:
            - { name: marello.form_changes_data_provider, class: '%marello_subscription.entity.subscription.class%', type: shippingAddress, priority: 30 }

    marello_subscription.provider.form_changes.possible_shipping_methods:
        class: 'Marello\Bundle\SubscriptionBundle\Provider\PossibleShippingMethodsProvider'
        arguments:
            - '@marello_order.factory.shipping_context'
            - '@marello_order.converter.shipping_prices'
            - '@marello_shipping.shipping_price.provider'
            - '@marello_shipping.integration.shipping_service_registry'
            - '@marello_subscription.mapper.subscription_to_order'
        tags:
            - { name: marello.form_changes_data_provider, class: '%marello_subscription.entity.subscription.class%', type: possible_shipping_methods, priority: 50 }

    marello_subscription.mapper.order_to_subscriptions:
        class: 'Marello\Bundle\SubscriptionBundle\Mapper\OrderToSubscriptionsMapper'
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'
            - '@oro_entity_config.manager.attribute_manager'


    marello_subscription.mapper.subscription_to_order:
        class: 'Marello\Bundle\SubscriptionBundle\Mapper\SubscriptionToOrderMapper'
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'
            - '@oro_entity_config.manager.attribute_manager'
            - '@doctrine'

    marello_subscription.listener.doctrine.order_with_pubscription_products_creation:
        class: 'Marello\Bundle\SubscriptionBundle\EventListener\Doctrine\OrderWithSubscriptionProductsCreationListener'
        arguments:
            - '@marello_subscription.mapper.order_to_subscriptions'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    marello_subscription.listener.order_item_status_update:
        class: 'Marello\Bundle\SubscriptionBundle\EventListener\OrderItemStatusUpdateListener'
        tags:
            - { name: kernel.event_listener, event: marello_order.order_item_status_update, method: onStatusUpdate }

    marello_subscription.listener.product_available_inventory_validation:
        class: 'Marello\Bundle\SubscriptionBundle\EventListener\ProductAvailableInventoryValidationListener'
        tags:
            - { name: kernel.event_listener, event: marello_product.product_available_inventory_validation, method: onValidation }

    marello_subscription.listener.datagrid.subscriptions_grid_address_filter_listener:
        class: 'Marello\Bundle\OrderBundle\EventListener\Datagrid\OrderGridAddressFilterListener'
        arguments:
            - '@oro_locale.dql.formatter.name'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.marello-subscriptions-grid, method: onBuildBefore }

    marello_subscription.twig.subscription_extension:
        class: 'Marello\Bundle\SubscriptionBundle\Twig\SubscriptionExtension'
        arguments:
            - '@doctrine'
        tags:
            - { name: twig.extension }

    marello_subscription.form.validator.subscription_product_attributes:
        class: 'Marello\Bundle\SubscriptionBundle\Validator\SubscriptionProductAttributesValidator'
        tags:
            - { name: validator.constraint_validator, alias: marello_subscription.subscription_product_attributes_validator }

    marello_subscription.additional_placeholder_data.customer_subscriptions:
        class: 'Marello\Bundle\SubscriptionBundle\Provider\AdditionalPlaceholderDataProvider'
        tags:
            - {name: marello_core.additional_placeholder_data }