connector:
    name: oro_importexport
    jobs:
        mage_store_import:
            title: "Store import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.store
                        processor: marello_magento.importexport.processor.store
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_store_rest_import:
            title: "Store import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.rest.store
                        processor: marello_magento.importexport.processor.rest.store
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_website_import:
            title: "Website import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.website
                        processor: marello_magento.importexport.processor.website
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_website_rest_import:
            title: "Website import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.rest.website
                        processor: marello_magento.importexport.processor.rest.website
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 25

        mage_product_import:
            title: "Product import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.product_connector
                        processor: marello_magento.importexport.processor.product
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 1

        mage_product_export:
            title: "Product export to Magento"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.product_export
                        processor: marello_magento.importexport.processor.product_export
                        writer:    marello_magento.importexport.writer.product_export
                    parameters:
                        batch_size: 1

        product_export_delete:
            title: "Product delete from Magento"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.product_export_delete
                        processor: marello_magento.importexport.processor.product_export_delete
                        writer:    marello_magento.importexport.writer.product_export_delete
                    parameters:
                        batch_size: 1

        mage_category_import:
            title: "Category import from Magento"
            type:  import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.category_connector
                        processor: marello_magento.importexport.processor.category
                        writer:    marello_magento.writer.proxy_entity_writer
                    parameters:
                        batch_size: 1

        mage_category_export:
            title: "Category export to Magento (product assignments only)"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.product_category_export
                        processor: marello_magento.importexport.processor.product_category_export
                        writer:    marello_magento.importexport.writer.product_category_export
                    parameters:
                        batch_size: 1

        mage_inventorylevel_import:
            title: "Sync inventory levels from Magento"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.inventory_level_connector
                        processor: marello_magento.importexport.processor.inventory_level
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 1

        mage_inventorylevel_export:
            title: "Sync inventory levels to Magento"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.inventory_level_export
                        processor: marello_magento.importexport.processor.inventory_level_export
                        writer:    marello_magento.importexport.writer.inventory_level_export
                    parameters:
                        batch_size: 1

        mage_price_import:
            title: "Sync price from Magento"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.price_connector
                        processor: marello_magento.importexport.processor.price
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 1

        mage_price_export:
            title: "Sync price to Magento"
            type:  export
            steps:
                export:
                    title: export
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.importexport.reader.price_export
                        processor: marello_magento.importexport.processor.price_export
                        writer:    marello_magento.importexport.writer.price_export
                    parameters:
                        batch_size: 1

        mage_order_import:
            title: "Sync Orders from Magento"
            type: import
            steps:
                import:
                    title: import
                    class: Oro\Bundle\BatchBundle\Step\ItemStep
                    services:
                        reader:    marello_magento.mage.order_connector
                        processor: marello_magento.importexport.processor.order
                        writer:    oro_integration.writer.persistent_batch_writer
                    parameters:
                        batch_size: 25
