services:
    marelloenterprise_instoreassistant.provider.auth_provider:
        class: MarelloEnterprise\Bundle\InstoreAssistantBundle\Provider\InstoreUserAuthenticationProvider
        arguments:
            - '@marelloenterprise_instoreassistant.manager.oro_user_manager'
            - '@security.encoder_factory'
            - '@oro_userpro.security.login_attempts_manager'

    marelloenterprise_instoreassistant.manager.oro_user_manager:
        class: MarelloEnterprise\Bundle\InstoreAssistantBundle\Manager\OroUserManager
        parent: oro_user.manager

    marelloenterprise_instoreassistant.api.rest.api_doc.route_options_resolver.user_profile:
        class: MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\ApiDoc\InstoreUserRestRouteOptionsResolver
        public: false
        arguments:
            - '@oro_api.value_normalizer'
        tags:
            - { name: oro_api.routing_options_resolver, priority: -10 }

    marelloenterprise_instoreassistant.api.handler.request_action_handler:
        class: MarelloEnterprise\Bundle\InstoreAssistantBundle\Api\Handler\InstoreAssistantRequestActionHandler
        public: true
        arguments:
            - ['rest']
            - '@oro_api.action_processor_bag'
            - '@oro_api.rest.filter_value_accessor_factory'
            - '@fos_rest.view_handler'