dynamic-imports:
    marelloservicepoint:
        - marelloservicepoint/js/app/views/embed-map-view
        - marelloservicepoint/js/app/views/image-popup-view
        - marelloservicepoint/js/app/views/businesshoursoverrides-item-view
        - marelloservicepoint/js/app/views/businesshoursoverrides-items-view
