services:
    marelloenterprise_packing.mapper.order_to_packingslip:
        class: 'Marello\Bundle\PackingBundle\Mapper\OrderToPackingSlipMapper'
        arguments:
            - '@oro_entity.entity_field_provider'
            - '@property_accessor'
            - '@marelloenterprise_inventory.provider.order_warehouse'

    marelloenterprise_packing.event_listener.create_packing_slip:
        class: 'Marello\Bundle\PackingBundle\EventListener\CreatePackingSlipEventListener'
        arguments:
            - '@marelloenterprise_packing.mapper.order_to_packingslip'
            - '@oro_entity.doctrine_helper'
            - true
        tags:
            - { name: kernel.event_listener, event: extendable_action.create_packingslip, method: onCreatePackingSlip, priority: 20 }
