services:
    _defaults:
        public: true

    Marello\Bundle\HealthCheckBundle\Controller\IntegrationStatusController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
