api:
    entity_aliases:
        Marello\Bundle\POSUserBundle\Api\Model\POSUserApi:
            alias: marelloposuser
            plural_alias: marelloposuser
    entities:
        Marello\Bundle\POSUserBundle\Api\Model\POSUserApi:
            documentation_resource: '@MarelloPOSUserBundle/Resources/doc/api/pos_user_api.md'
            identifier_field_names: [id]
            fields:
                id:
                    data_type:   integer
                    description: The identifier of a UserApi.
                apiKey:
                    data_type:    string
                    description:  Api key
            actions:
                get: false
                get_list: false
                create: false
                update: false
                delete: false
                delete_list: false
                get_subresource: false
                get_relationship: false
                update_relationship: false
                add_relationship: false
                delete_relationship: false
