aliases:
    marello/sidebar/widget/notification_messages$: marellonotificationmessage/sidebar_widgets/notification_messages/js/widget
dynamic-imports:
    commons:
        - marello/sidebar/widget/notification_messages
