datagrids:
    marello-inventory-item:
        source:
            type: orm
            query:
                select:
                    - i.id
                    - p.denormalizedDefaultName as productName
                    - p.sku as productSku
                    - COALESCE(SUM(il.inventory), 0) AS inventoryQty
                    - COALESCE(SUM(il.allocatedInventory), 0) AS allocatedInventoryQty
                    - COALESCE(SUM(il.inventory - il.allocatedInventory), 0) AS virtualInventoryQty
                from:
                    - { table: MarelloInventoryBundle:InventoryItem, alias: i }
                join:
                    left:
                        - { join: i.product, alias: p }
                        - { join: i.inventoryLevels, alias: il }
                groupBy: i.id
        columns:
            productSku:
                data_name:          productSku
                label:              marello.product.sku.label
                type:               twig
                frontend_type:      html
                template:           MarelloProductBundle:Product/Datagrid:productSku.html.twig
            productName:
                label:              marello.product.entity_label
                frontend_type:      string
                data_name:          productName
            inventoryQty:
                label:              marello.inventory.inventorylevel.inventory.label
                frontend_type:      number
                data_name:          inventoryQty
            allocatedInventoryQty:
                label:              marello.inventory.inventorylevel.allocated_inventory.label
                frontend_type:      number
                data_name:          allocatedInventoryQty
            virtualInventoryQty:
                label:              marello.inventory.inventorylevel.virtual_inventory.label
                frontend_type:      number
                data_name:          virtualInventoryQty
        sorters:
            columns:
                productSku:             { data_name: p.sku }
                productName:            { data_name: p.denormalizedDefaultName }
                inventoryQty:           { data_name: inventoryQty }
                allocatedInventoryQty:  { data_name: allocatedInventoryQty }
                virtualInventoryQty:    { data_name: virtualInventoryQty }
            default:
                productSku: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                productSku:
                    type:             string
                    data_name:        p.sku
                productName:
                    type:             string
                    data_name:        p.denormalizedDefaultName
                inventoryQty:
                    type:             number
                    data_name:        inventoryQty
                    filter_by_having: true
                allocatedInventoryQty:
                    type:             number
                    data_name:        allocatedInventoryQty
                    filter_by_having: true
                virtualInventoryQty:
                    type:             number
                    data_name:        virtualInventoryQty
                    filter_by_having: true
        properties:
            id: ~
            inventory_view_link:
                type:       url
                route:      marello_inventory_inventory_view
                params:     [ id ]
            inventory_update_link:
                type:       url
                route:      marello_inventory_inventory_update
                params:     [ id ]
        actions:
            view:
                type:           navigate
                label:          oro.grid.action.view
                link:           inventory_view_link
                icon:           eye
                acl_recource:   marello_product_view
                rowAction:      true
            update:
                type:           navigate
                label:          marello.inventory.update
                icon:           edit
                link:           inventory_update_link
        options:
            export: true

    marello-inventory-log:
        source:
            type: orm
            query:
                select:
                    - lr
                    - (lr.inventoryAlteration) AS inventoryDiff
                    - (lr.allocatedInventoryAlteration) AS allocatedInventoryDiff
                from:
                    - { table: MarelloInventoryBundle:InventoryLevelLogRecord, alias: lr }
                join:
                    left:
                        - { join: lr.inventoryLevel, alias: il }
                where:
                    and:
                        - IDENTITY(il.inventoryItem) = :inventoryItemId
            bind_parameters:
                inventoryItemId: inventoryItemId
        columns:
            inventoryDiff:
                data_name:      inventoryDiff
                label:          marello.inventory.inventorylevellogrecord.inventory_alteration.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/InventoryLevel/diff.html.twig
            allocatedInventoryDiff:
                data_name:      allocatedInventoryDiff
                label:          marello.inventory.inventorylevellogrecord.allocated_inventory_alteration.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/InventoryLevel/diff.html.twig
            changeTrigger:
                data_name:      changeTrigger
                label:          marello.inventory.inventorylevellogrecord.change_trigger.label
                type:           translatable
                domain:         MarelloInventoryLevelChangeTrigger
                frontend_type:  string
            user:
                label:          marello.inventory.inventorylevellogrecord.user.label
                frontend_type:  string
            subject:
                label:          marello.inventory.inventorylevellogrecord.subject_type.label
                type:           twig
                frontend_type:  html
                template:       MarelloInventoryBundle::Datagrid/InventoryLevel/subject.html.twig
            createdAt:
                label:          oro.ui.created_at
                frontend_type:  datetime
        sorters:
            columns:
                createdAt:
                    data_name:  lr.createdAt
                inventoryDiff:
                    data_name:  inventoryDiff
                allocatedInventoryDiff:
                    data_name:  allocatedInventoryDiff
            default:
                createdAt:      DESC
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 10

    marello-inventory-log-extended:
        extends: marello-inventory-log
        filters:
            columns:
                inventoryDiff:
                    type:             number
                    data_name:        inventoryDiff
                allocatedInventoryDiff:
                    type:             number
                    data_name:        allocatedInventoryDiff
                changeTrigger:
                    type:             string
                    data_name:        l.changeTrigger
                createdAt:
                    type:             datetime
                    data_name:        createdAt
        options:
            toolbarOptions:
                pageSize:
                    default_per_page: 50

    marello-inventory-levels:
        source:
            type: orm
            query:
                select:
                    - il
                    - wht.label as warehouseTypeLabel
                    - COALESCE(il.inventory, 0) AS inventoryQty
                    - COALESCE(il.allocatedInventory, 0) AS allocatedInventoryQty
                    - COALESCE(il.inventory - il.allocatedInventory, 0) AS virtualInventoryQty
                from:
                    - { table: MarelloInventoryBundle:InventoryLevel, alias: il }
                join:
                    left:
                        - { join: il.warehouse, alias: wh }
                        - { join: wh.warehouseType, alias: wht }
                where:
                    and:
                        - IDENTITY(il.inventoryItem) = :inventoryItemId
                groupBy: il.id
            bind_parameters:
                inventoryItemId: inventoryItemId
        columns:
            warehouse:
                label:              marello.inventory.inventorylevel.warehouse.label
                frontend_type:      string
            pickLocation:
                label:              marello.inventory.inventorylevel.pick_location.label
                frontend_type:      string
            warehouseTypeLabel:
                label:              marello.inventory.warehousetype.entity_label
                frontend_type:      string
            inventoryQty:
                label:              marello.inventory.inventorylevel.inventory.label
                frontend_type:      number
                data_name:          inventoryQty
            allocatedInventoryQty:
                label:              marello.inventory.inventorylevel.allocated_inventory.label
                frontend_type:      number
                data_name:          allocatedInventoryQty
            virtualInventoryQty:
                label:              marello.inventory.inventorylevel.virtual_inventory.label
                frontend_type:      number
                data_name:          virtualInventoryQty
            updatedAt:
                label:              oro.ui.updated_at
                frontend_type:      datetime


    marello-balanced-inventory-levels-grid:
        source:
            type: orm
            query:
                select:
                    - balancedInventoryLevel
                    - p.denormalizedDefaultName as productName
                    - p.sku as productSku
                    - scg.name as salesChannelGroupName
                from:
                    - { table: MarelloInventoryBundle:BalancedInventoryLevel, alias: balancedInventoryLevel }
                join:
                    left:
                        - { join: balancedInventoryLevel.product, alias: p }
                        - { join: balancedInventoryLevel.salesChannelGroup, alias: scg }
        columns:
            productName:
                label:              marello.product.names.label
                frontend_type:      string
                data_name:          productName
                renderable:         false
            productSku:
                data_name:          productSku
                label:              marello.product.sku.label
                type:               twig
                frontend_type:      html
                template:           MarelloProductBundle:Product/Datagrid:productSku.html.twig
            inventoryQty:
                label:              marello.inventory.balancedinventorylevel.inventory.label
                frontend_type:      number
                data_name:          inventoryQty
            balancedInventoryQty:
                label:              marello.inventory.balancedinventorylevel.balanced_inventory_qty.label
                frontend_type:      number
                data_name:          balancedInventoryQty
            reservedInventoryQty:
                label:              marello.inventory.balancedinventorylevel.reserved_inventory_qty.label
                frontend_type:      number
                data_name:          reservedInventoryQty
            salesChannelGroupName:
                label:              marello.sales.saleschannelgroup.entity_label
                frontend_type:      string
                data_name:          salesChannelGroupName
            createdAt:
                label:              oro.ui.created_at
                frontend_type:      datetime
            updatedAt:
                label:              oro.ui.updated_at
                frontend_type:      datetime
                renderable:         false
        filters:
            columns:
                productSku:
                    type:             string
                    data_name:        productSku
                productName:
                    type:             string
                    data_name:        productName
        sorters:
            columns:
                createdAt:
                    data_name:  balancedInventoryLevel.createdAt
                salesChannelGroupName:
                    data_name:  salesChannelGroupName
                productName:
                    data_name:  productName
                productSku:
                    data_name:  productSku
                inventoryQty:
                    data_name:  balancedInventoryLevel.inventory
                balancedInventoryQty:
                    data_name:  balancedInventoryLevel.balancedInventory
                reservedInventoryQty:
                    data_name:  balancedInventoryLevel.reservedInventory
            default:
                createdAt:      DESC
