operations:
    marello_notificationmessage_resolve:
        label: marello.notificationmessage.actions.resolve.label
        button_options:
            icon: fa-check
        enabled: true
        routes:
            - marello_notificationmessage_view
        acl_resource: marello_notificationmessage_view
        applications: [default]
        preconditions:
            '@equal': [$.data.resolved.id, 'no']
        actions:
            - '@request_enum_entity':
                  enum_code: auth_status
                  identifier: 'yes'
                  attribute: $.data.resolved
            - '@flush_entity': $.data
            - '@flash_message':
                  message: marello.notificationmessage.actions.resolve.success
                  type: 'success'
