oro_entity:
    entity_aliases:
        Marello\Bundle\NotificationMessageBundle\Entity\NotificationMessage:
            alias:        marellonotificationmessage
            plural_alias: marellonotificationmessages
